import type { DashboardSectionDefinition } from "../dashboardTypes.js";
import {
  TTS_ENGINE_OPTIONS,
  TTS_LANGUAGE_OPTIONS,
  TTS_VOICE_OPTIONS,
  BUTTON_STYLE_OPTIONS,
  TICKET_FLOW_OPTIONS,
  WELCOME_MODE_OPTIONS,
  WELCOME_STYLE_OPTIONS,
  WELCOME_COLOR_MODE_OPTIONS,
  WELCOME_MEDIA_MODE_OPTIONS,
  WELCOME_WEBHOOK_NAME_OPTIONS,
  WELCOME_WEBHOOK_AVATAR_OPTIONS,
  WELCOME_EMBED_IMAGE_MODE_OPTIONS,
  WELCOME_EMBED_MAIN_IMAGE_MODE_OPTIONS,
  BIRTHDAY_LEAP_MODE_OPTIONS,
  WELCOME_TEMPLATE_VARIABLES,
  FORM_TEMPLATE_VARIABLES,
  BIRTHDAY_REGISTER_VARIABLES,
  BIRTHDAY_ANNOUNCE_VARIABLES,
  BIRTHDAY_CALENDAR_VARIABLES,
  messageField,
  ticketOptionFields
} from "../dashboardCatalogShared.js";

export const welcomeSection: DashboardSectionDefinition = {
  id: "welcome", label: "Boas-vindas", emoji: "👋", description: "Mensagem pública, DM, cargos automáticos e identidade de envio.",
  groups: ["Ativação", "Mensagem de entrada", "Mensagem privada", "Aparência", "Cargos"],
  groupMetadata: {
    "Mensagem de entrada": {
      kind: "message",
      variables: WELCOME_TEMPLATE_VARIABLES,
      settingsFieldIds: [
        "welcome.channel_id", "welcome.render_mode", "welcome.delete_on_leave_enabled",
      ],
      editors: [{
        id: "welcome-public",
        label: "Mensagem pública",
        description: "Edite a mensagem e a identidade usada no envio.",
        presentation: "adaptive",
        fieldIds: [
          "welcome.public.title", "welcome.public.body", "welcome.public.footer",
          "welcome.style", "welcome.accent_color", "welcome.accent_color_mode", "welcome.media_mode", "welcome.media_url",
          "welcome.embed.content", "welcome.embed.author_name", "welcome.embed.author_icon_mode", "welcome.embed.author_icon_url",
          "welcome.embed.author_url", "welcome.embed.title", "welcome.embed.title_url", "welcome.embed.description",
          "welcome.embed.color", "welcome.embed.color_mode", "welcome.embed.thumbnail_mode", "welcome.embed.thumbnail_url",
          "welcome.embed.image_mode", "welcome.embed.image_url", "welcome.embed.footer_text",
          "welcome.embed.footer_icon_mode", "welcome.embed.footer_icon_url",
        ],
        senderFieldIds: [
          "welcome.webhook.enabled", "welcome.webhook.name_mode", "welcome.webhook.name",
          "welcome.webhook.avatar_mode", "welcome.webhook.avatar_url",
        ],
      }],
    },
    "Mensagem privada": {
      kind: "message",
      variables: WELCOME_TEMPLATE_VARIABLES,
      settingsFieldIds: ["welcome.dm_enabled", "welcome.dm_render_mode"],
      editors: [{
        id: "welcome-dm",
        label: "Mensagem privada",
        description: "Conteúdo enviado diretamente ao novo membro.",
        presentation: "adaptive",
        fieldIds: ["welcome.dm.title", "welcome.dm.body", "welcome.dm.footer"],
      }],
    },
  },
  fields: [
    { id: "welcome.enabled", label: "Boas-vindas", description: "Ative para enviar novas mensagens de entrada. As configurações ficam preservadas ao desativar.", type: "boolean", scope: "welcome", path: "enabled", group: "Ativação" },
    { id: "welcome.channel_id", label: "Canal de boas-vindas", type: "channel", scope: "welcome", path: "channel_id", group: "Mensagem de entrada" },
    { id: "welcome.render_mode", label: "Formato público", type: "select", scope: "welcome", path: "render_mode", options: WELCOME_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.style", label: "Estilo Components V2", type: "select", scope: "welcome", path: "style", options: WELCOME_STYLE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.delete_on_leave_enabled", label: "Apagar se o membro sair em até 24h", type: "boolean", scope: "welcome", path: "delete_on_leave_enabled", group: "Mensagem de entrada" },
    messageField("welcome.public.title", "Título público", "welcome", "public.title", "Mensagem de entrada", 256),
    messageField("welcome.public.body", "Mensagem pública", "welcome", "public.body", "Mensagem de entrada"),
    messageField("welcome.public.footer", "Rodapé público", "welcome", "public.footer", "Mensagem de entrada", 300),
    messageField("welcome.embed.content", "Texto acima do embed", "welcome", "embed.content", "Mensagem de entrada"),
    messageField("welcome.embed.author_name", "Autor", "welcome", "embed.author_name", "Mensagem de entrada", 256),
    { id: "welcome.embed.author_icon_mode", label: "Ícone do autor", type: "select", scope: "welcome", path: "embed.author_icon_mode", options: WELCOME_EMBED_IMAGE_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.embed.author_icon_url", label: "URL do ícone do autor", type: "url", scope: "welcome", path: "embed.author_icon_url", maxLength: 1000, group: "Mensagem de entrada" },
    { id: "welcome.embed.author_url", label: "URL do autor", type: "url", scope: "welcome", path: "embed.author_url", maxLength: 1000, group: "Mensagem de entrada" },
    messageField("welcome.embed.title", "Título do embed", "welcome", "embed.title", "Mensagem de entrada", 256),
    { id: "welcome.embed.title_url", label: "URL do título", type: "url", scope: "welcome", path: "embed.title_url", maxLength: 1000, group: "Mensagem de entrada" },
    messageField("welcome.embed.description", "Descrição do embed", "welcome", "embed.description", "Mensagem de entrada"),
    { id: "welcome.embed.color", label: "Cor do embed", type: "color", scope: "welcome", path: "embed.color", group: "Mensagem de entrada" },
    { id: "welcome.embed.color_mode", label: "Modo da cor", type: "select", scope: "welcome", path: "embed.color_mode", options: WELCOME_COLOR_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.embed.thumbnail_mode", label: "Thumbnail", type: "select", scope: "welcome", path: "embed.thumbnail_mode", options: WELCOME_EMBED_IMAGE_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.embed.thumbnail_url", label: "URL da thumbnail", type: "url", scope: "welcome", path: "embed.thumbnail_url", maxLength: 1000, group: "Mensagem de entrada" },
    { id: "welcome.embed.image_mode", label: "Imagem principal", type: "select", scope: "welcome", path: "embed.image_mode", options: WELCOME_EMBED_MAIN_IMAGE_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.embed.image_url", label: "URL da imagem", type: "url", scope: "welcome", path: "embed.image_url", maxLength: 1000, group: "Mensagem de entrada" },
    messageField("welcome.embed.footer_text", "Rodapé do embed", "welcome", "embed.footer_text", "Mensagem de entrada", 1000),
    { id: "welcome.embed.footer_icon_mode", label: "Ícone do rodapé", type: "select", scope: "welcome", path: "embed.footer_icon_mode", options: WELCOME_EMBED_IMAGE_MODE_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.embed.footer_icon_url", label: "URL do ícone do rodapé", type: "url", scope: "welcome", path: "embed.footer_icon_url", maxLength: 1000, group: "Mensagem de entrada" },
    { id: "welcome.dm_enabled", label: "Enviar mensagem no privado", type: "boolean", scope: "welcome", path: "dm_enabled", group: "Mensagem privada" },
    { id: "welcome.dm_render_mode", label: "Formato da DM", type: "select", scope: "welcome", path: "dm_render_mode", options: WELCOME_MODE_OPTIONS, group: "Mensagem privada" },
    messageField("welcome.dm.title", "Título da DM", "welcome", "dm.title", "Mensagem privada", 256),
    messageField("welcome.dm.body", "Mensagem da DM", "welcome", "dm.body", "Mensagem privada"),
    messageField("welcome.dm.footer", "Rodapé da DM", "welcome", "dm.footer", "Mensagem privada", 300),
    { id: "welcome.decorative_emoji_enabled", label: "Emojis decorativos", type: "boolean", scope: "welcome", path: "decorative_emoji_enabled", group: "Aparência" },
    { id: "welcome.accent_color", label: "Cor de destaque", type: "color", scope: "welcome", path: "accent_color", group: "Aparência" },
    { id: "welcome.accent_color_mode", label: "Modo da cor", type: "select", scope: "welcome", path: "accent_color_mode", options: WELCOME_COLOR_MODE_OPTIONS, group: "Aparência" },
    { id: "welcome.media_mode", label: "Imagem ou banner", type: "select", scope: "welcome", path: "media_mode", options: WELCOME_MEDIA_MODE_OPTIONS, group: "Aparência" },
    { id: "welcome.media_url", label: "URL da imagem ou banner", type: "url", scope: "welcome", path: "media_url", maxLength: 1000, group: "Aparência" },
    { id: "welcome.auto_role_ids", label: "Cargos automáticos", description: "Cargos aplicados quando um membro entra.", type: "role_multi", scope: "welcome", path: "auto_role_ids", group: "Cargos" },
    { id: "welcome.webhook.enabled", label: "Enviar como webhook", description: "Use nome e avatar personalizados nesta mensagem.", type: "boolean", scope: "welcome", path: "webhook.enabled", group: "Mensagem de entrada" },
    { id: "welcome.webhook.name_mode", label: "Nome exibido", type: "select", scope: "welcome", path: "webhook.name_mode", options: WELCOME_WEBHOOK_NAME_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.webhook.name", label: "Nome personalizado", type: "text", scope: "welcome", path: "webhook.name", maxLength: 80, group: "Mensagem de entrada" },
    { id: "welcome.webhook.avatar_mode", label: "Avatar exibido", type: "select", scope: "welcome", path: "webhook.avatar_mode", options: WELCOME_WEBHOOK_AVATAR_OPTIONS, group: "Mensagem de entrada" },
    { id: "welcome.webhook.avatar_url", label: "URL do avatar", type: "url", scope: "welcome", path: "webhook.avatar_url", maxLength: 1000, group: "Mensagem de entrada" },
  ],
};
