import type { DashboardSectionDefinition } from "../dashboardTypes.js";
import {
  TTS_ENGINE_OPTIONS,
  TTS_LANGUAGE_OPTIONS,
  TTS_VOICE_OPTIONS,
  BUTTON_STYLE_OPTIONS,
  TICKET_FLOW_OPTIONS,
  WELCOME_MODE_OPTIONS,
  WELCOME_STYLE_OPTIONS,
  WELCOME_COLOR_MODE_OPTIONS,
  WELCOME_MEDIA_MODE_OPTIONS,
  WELCOME_WEBHOOK_NAME_OPTIONS,
  WELCOME_WEBHOOK_AVATAR_OPTIONS,
  WELCOME_EMBED_IMAGE_MODE_OPTIONS,
  WELCOME_EMBED_MAIN_IMAGE_MODE_OPTIONS,
  BIRTHDAY_LEAP_MODE_OPTIONS,
  WELCOME_TEMPLATE_VARIABLES,
  FORM_TEMPLATE_VARIABLES,
  BIRTHDAY_REGISTER_VARIABLES,
  BIRTHDAY_ANNOUNCE_VARIABLES,
  BIRTHDAY_CALENDAR_VARIABLES,
  messageField,
  ticketOptionFields
} from "../dashboardCatalogShared.js";

export const formsSection: DashboardSectionDefinition = {
  id: "forms", label: "Formulários", emoji: "📝", description: "Painel, perguntas, respostas e aprovação da verificação.",
  groups: ["Ativação", "Canais", "Painel", "Perguntas", "Resposta", "Aprovação"],
  groupMetadata: {
    Painel: {
      kind: "message",
      editors: [{
        id: "forms-panel",
        label: "Painel público",
        presentation: "components_v2",
        description: "Título, descrição, botão, imagem, cor e prévia do painel.",
        fieldIds: [
          "forms.panel.title", "forms.panel.description", "forms.panel.button_label", "forms.panel.button_emoji",
          "forms.panel.button_style", "forms.panel.media_url", "forms.panel.accent_color",
        ],
      }],
    },
    Resposta: {
      kind: "message",
      variables: FORM_TEMPLATE_VARIABLES,
      editors: [{
        id: "forms-response",
        label: "Resposta enviada à equipe",
        presentation: "components_v2",
        description: "Conteúdo, imagem, cor e prévia do resumo recebido pela equipe.",
        fieldIds: [
          "forms.response.title", "forms.response.intro", "forms.response.footer",
          "forms.response.media_url", "forms.response.accent_color",
        ],
      }],
    },
    Aprovação: {
      kind: "message",
      variables: FORM_TEMPLATE_VARIABLES,
      settingsFieldIds: [
        "forms.approval.enabled", "forms.approval.role_id", "forms.approval.approve_label",
        "forms.approval.approve_emoji", "forms.approval.approve_style", "forms.approval.reject_label",
        "forms.approval.reject_emoji", "forms.approval.reject_style",
      ],
      editors: [
        {
          id: "forms-approve-dm",
          label: "Mensagem ao aprovar",
          presentation: "components_v2",
          description: "Mensagem privada enviada após a aprovação.",
          fieldIds: ["forms.approval.approve_dm"],
        },
        {
          id: "forms-reject-dm",
          label: "Mensagem ao rejeitar",
          presentation: "components_v2",
          description: "Mensagem privada enviada após a rejeição.",
          fieldIds: ["forms.approval.reject_dm"],
        },
      ],
    },
  },
  fields: [
    { id: "forms.enabled", label: "Formulários", description: "Ative para aceitar novos envios. Respostas pendentes continuam disponíveis ao desativar.", type: "boolean", scope: "guild", path: "forms.enabled", group: "Ativação" },
    { id: "forms.form_channel_id", label: "Canal do formulário", type: "channel", scope: "guild", path: "forms.form_channel_id", group: "Canais" },
    { id: "forms.responses_channel_id", label: "Canal de respostas", type: "channel", scope: "guild", path: "forms.responses_channel_id", group: "Canais" },
    { id: "forms.panel.title", label: "Título do painel", type: "text", scope: "guild", path: "forms.panel.title", maxLength: 250, group: "Painel" },
    { id: "forms.panel.description", label: "Descrição do painel", type: "textarea", scope: "guild", path: "forms.panel.description", maxLength: 1000, group: "Painel" },
    { id: "forms.panel.button_label", label: "Texto do botão", type: "text", scope: "guild", path: "forms.panel.button_label", maxLength: 80, group: "Painel" },
    { id: "forms.panel.button_emoji", label: "Emoji do botão", type: "text", scope: "guild", path: "forms.panel.button_emoji", maxLength: 32, group: "Painel" },
    { id: "forms.panel.button_style", label: "Cor do botão", type: "select", scope: "guild", path: "forms.panel.button_style", options: BUTTON_STYLE_OPTIONS, group: "Painel" },
    { id: "forms.panel.media_url", label: "Imagem do painel", type: "url", scope: "guild", path: "forms.panel.media_url", maxLength: 400, group: "Painel" },
    { id: "forms.panel.accent_color", label: "Cor de destaque", type: "color", scope: "guild", path: "forms.panel.accent_color", group: "Painel" },
    { id: "forms.modal.title", label: "Título do formulário", type: "text", scope: "guild", path: "forms.modal.title", maxLength: 45, group: "Perguntas" },
    { id: "forms.modal.fields", label: "Perguntas", description: "Até cinco campos exibidos no modal do Discord.", type: "form_fields", scope: "guild", path: "forms.modal.fields", group: "Perguntas" },
    { id: "forms.response.title", label: "Título da resposta", type: "text", scope: "guild", path: "forms.response.title", maxLength: 250, group: "Resposta" },
    { id: "forms.response.intro", label: "Texto introdutório", type: "textarea", scope: "guild", path: "forms.response.intro", maxLength: 700, group: "Resposta" },
    { id: "forms.response.footer", label: "Rodapé", type: "textarea", scope: "guild", path: "forms.response.footer", maxLength: 700, group: "Resposta" },
    { id: "forms.response.media_url", label: "Imagem da resposta", type: "url", scope: "guild", path: "forms.response.media_url", maxLength: 400, group: "Resposta" },
    { id: "forms.response.accent_color", label: "Cor da resposta", type: "color", scope: "guild", path: "forms.response.accent_color", group: "Resposta" },
    { id: "forms.approval.enabled", label: "Ativar aprovação da staff", type: "boolean", scope: "guild", path: "forms.approval.enabled", group: "Aprovação" },
    { id: "forms.approval.role_id", label: "Cargo aplicado ao aprovar", type: "role", scope: "guild", path: "forms.approval.role_id", group: "Aprovação" },
    { id: "forms.approval.approve_label", label: "Texto do botão Aprovar", type: "text", scope: "guild", path: "forms.approval.approve_label", maxLength: 80, group: "Aprovação" },
    { id: "forms.approval.approve_emoji", label: "Emoji de aprovação", type: "text", scope: "guild", path: "forms.approval.approve_emoji", maxLength: 32, group: "Aprovação" },
    { id: "forms.approval.approve_style", label: "Cor do botão Aprovar", type: "select", scope: "guild", path: "forms.approval.approve_style", options: BUTTON_STYLE_OPTIONS, group: "Aprovação" },
    { id: "forms.approval.reject_label", label: "Texto do botão Rejeitar", type: "text", scope: "guild", path: "forms.approval.reject_label", maxLength: 80, group: "Aprovação" },
    { id: "forms.approval.reject_emoji", label: "Emoji de rejeição", type: "text", scope: "guild", path: "forms.approval.reject_emoji", maxLength: 32, group: "Aprovação" },
    { id: "forms.approval.reject_style", label: "Cor do botão Rejeitar", type: "select", scope: "guild", path: "forms.approval.reject_style", options: BUTTON_STYLE_OPTIONS, group: "Aprovação" },
    { id: "forms.approval.approve_dm", label: "DM ao aprovar", type: "textarea", scope: "guild", path: "forms.approval.approve_dm", maxLength: 1000, group: "Aprovação" },
    { id: "forms.approval.reject_dm", label: "DM ao rejeitar", type: "textarea", scope: "guild", path: "forms.approval.reject_dm", maxLength: 1000, group: "Aprovação" },
  ],
};
