import type { DashboardSectionDefinition } from "../dashboardTypes.js";
import {
  TTS_ENGINE_OPTIONS,
  TTS_LANGUAGE_OPTIONS,
  TTS_VOICE_OPTIONS,
  BUTTON_STYLE_OPTIONS,
  TICKET_FLOW_OPTIONS,
  WELCOME_MODE_OPTIONS,
  WELCOME_STYLE_OPTIONS,
  WELCOME_COLOR_MODE_OPTIONS,
  WELCOME_MEDIA_MODE_OPTIONS,
  WELCOME_WEBHOOK_NAME_OPTIONS,
  WELCOME_WEBHOOK_AVATAR_OPTIONS,
  WELCOME_EMBED_IMAGE_MODE_OPTIONS,
  WELCOME_EMBED_MAIN_IMAGE_MODE_OPTIONS,
  BIRTHDAY_LEAP_MODE_OPTIONS,
  WELCOME_TEMPLATE_VARIABLES,
  FORM_TEMPLATE_VARIABLES,
  BIRTHDAY_REGISTER_VARIABLES,
  BIRTHDAY_ANNOUNCE_VARIABLES,
  BIRTHDAY_CALENDAR_VARIABLES,
  messageField,
  ticketOptionFields
} from "../dashboardCatalogShared.js";

export const ticketsSection: DashboardSectionDefinition = {
  id: "tickets", label: "Tickets", emoji: "🎫", description: "Painel, fluxos de atendimento, permissões e transcrições.",
  groups: ["Ativação", "Painel", "Atendimento", "Comportamento", "Fluxos", "Textos", "Denúncias", "Permissões"],
  groupMetadata: {
    Painel: {
      kind: "message",
      settingsFieldIds: ["tickets.panel.channel_id"],
      editors: [{
        id: "tickets-panel",
        label: "Painel público",
        presentation: "components_v2",
        description: "Título, descrição, seletor, imagens, cor e prévia do painel de atendimento.",
        fieldIds: [
          "tickets.panel.title", "tickets.panel.description", "tickets.panel.placeholder",
          "tickets.panel.accent_color", "tickets.panel.image_url", "tickets.panel.side_image_url",
        ],
      }],
    },
    Textos: {
      kind: "message",
      editors: [
        { id: "tickets-partnership-texts", label: "Parceria", description: "Confirmação e mensagem de abertura.", fieldIds: ["tickets.texts.partnership_confirm", "tickets.texts.partnership_opening"] },
        { id: "tickets-report-texts", label: "Denúncia", description: "Aviso do formulário e mensagem de abertura.", fieldIds: ["tickets.texts.report_modal_notice", "tickets.texts.report_opening"] },
        { id: "tickets-other-texts", label: "Outros", description: "Mensagem de abertura do atendimento geral.", fieldIds: ["tickets.texts.other_opening"] },
        { id: "tickets-suggestion-texts", label: "Sugestão", description: "Mensagem após publicar uma sugestão.", fieldIds: ["tickets.texts.suggestion_published"] },
        { id: "tickets-close-texts", label: "Encerramento", description: "Aviso exibido ao fechar o ticket.", fieldIds: ["tickets.texts.close_notice"] },
      ],
    },
  },
  fields: [
    { id: "tickets.feature_enabled", label: "Tickets", description: "Ative para permitir novos atendimentos. Tickets já abertos continuam funcionando ao desativar.", type: "boolean", scope: "guild", path: "tickets.feature_enabled", group: "Ativação" },
    { id: "tickets.panel.channel_id", label: "Canal do painel", type: "channel", scope: "guild", path: "tickets.panel.channel_id", group: "Painel" },
    { id: "tickets.panel.title", label: "Título", type: "text", scope: "guild", path: "tickets.panel.title", maxLength: 250, group: "Painel" },
    { id: "tickets.panel.description", label: "Descrição", type: "textarea", scope: "guild", path: "tickets.panel.description", maxLength: 1200, group: "Painel" },
    { id: "tickets.panel.placeholder", label: "Placeholder do seletor", type: "text", scope: "guild", path: "tickets.panel.placeholder", maxLength: 150, group: "Painel" },
    { id: "tickets.panel.accent_color", label: "Cor de destaque", type: "color", scope: "guild", path: "tickets.panel.accent_color", group: "Painel" },
    { id: "tickets.panel.image_url", label: "Imagem principal", type: "url", scope: "guild", path: "tickets.panel.image_url", maxLength: 1000, group: "Painel" },
    { id: "tickets.panel.side_image_url", label: "Imagem lateral", type: "url", scope: "guild", path: "tickets.panel.side_image_url", maxLength: 1000, group: "Painel" },
    { id: "tickets.channels.category_id", label: "Categoria dos tickets", type: "channel", scope: "guild", path: "tickets.channels.category_id", group: "Atendimento" },
    { id: "tickets.channels.logs_channel_id", label: "Canal de logs", type: "channel", scope: "guild", path: "tickets.channels.logs_channel_id", group: "Atendimento" },
    { id: "tickets.channels.suggestions_channel_id", label: "Canal de sugestões", type: "channel", scope: "guild", path: "tickets.channels.suggestions_channel_id", group: "Atendimento" },
    { id: "tickets.roles.staff_role_id", label: "Staff geral", type: "role", scope: "guild", path: "tickets.roles.staff_role_id", group: "Atendimento" },
    { id: "tickets.roles.partnership_staff_role_id", label: "Staff de parcerias", type: "role", scope: "guild", path: "tickets.roles.partnership_staff_role_id", group: "Atendimento" },
    { id: "tickets.roles.report_staff_role_id", label: "Staff de denúncias", type: "role", scope: "guild", path: "tickets.roles.report_staff_role_id", group: "Atendimento" },
    { id: "tickets.roles.other_staff_role_id", label: "Staff de outros", type: "role", scope: "guild", path: "tickets.roles.other_staff_role_id", group: "Atendimento" },
    { id: "tickets.options.allow_multiple_open_tickets", label: "Permitir vários tickets por usuário", type: "boolean", scope: "guild", path: "tickets.options.allow_multiple_open_tickets", group: "Comportamento" },
    { id: "tickets.options.transcript_on_close", label: "Gerar transcrição ao fechar", type: "boolean", scope: "guild", path: "tickets.options.transcript_on_close", group: "Comportamento" },
    { id: "tickets.options.use_server_webhook", label: "Usar identidade do servidor", type: "boolean", scope: "guild", path: "tickets.options.use_server_webhook", group: "Comportamento" },
    { id: "tickets.enabled.partnership", label: "Ativar Parceria", type: "boolean", scope: "guild", path: "tickets.option_items.partnership.enabled", group: "Fluxos" },
    { id: "tickets.enabled.report", label: "Ativar Denúncia", type: "boolean", scope: "guild", path: "tickets.option_items.report.enabled", group: "Fluxos" },
    { id: "tickets.enabled.suggestion", label: "Ativar Sugestão", type: "boolean", scope: "guild", path: "tickets.option_items.suggestion.enabled", group: "Fluxos" },
    { id: "tickets.enabled.other", label: "Ativar Outros", type: "boolean", scope: "guild", path: "tickets.option_items.other.enabled", group: "Fluxos" },
    ...ticketOptionFields("partnership", "Parceria"),
    ...ticketOptionFields("report", "Denúncia"),
    ...ticketOptionFields("suggestion", "Sugestão"),
    ...ticketOptionFields("other", "Outros"),
    ...Object.entries({
      partnership_confirm: "Confirmação de parceria", partnership_opening: "Abertura de parceria", report_modal_notice: "Aviso da denúncia",
      report_opening: "Abertura da denúncia", other_opening: "Abertura de Outros", suggestion_published: "Sugestão publicada", close_notice: "Aviso de fechamento",
    }).map(([key, label]) => ({ id: `tickets.texts.${key}`, label, type: "textarea" as const, scope: "guild" as const, path: `tickets.texts.${key}`, maxLength: 1800, group: "Textos" })),
    { id: "tickets.report_types", label: "Tipos de denúncia", description: "Uma opção por linha.", type: "string_list", scope: "guild", path: "tickets.report_types", group: "Denúncias" },
    ...["everyone", "staff", "creator"].flatMap((scope) => [
      "view_channel", "send_messages", "read_message_history", "attach_files", "embed_links", "add_reactions",
      ...(scope === "staff" ? ["manage_messages", "manage_channels"] : []),
      ...(scope === "creator" ? ["mention_everyone"] : []),
    ].map((permission) => ({
      id: `tickets.permissions.${scope}.${permission}`,
      label: `${scope === "everyone" ? "Demais membros" : scope === "staff" ? "Equipe" : "Autor"}: ${({
        view_channel: "ver o canal",
        send_messages: "enviar mensagens",
        read_message_history: "ler o histórico",
        attach_files: "enviar arquivos",
        embed_links: "incorporar links",
        add_reactions: "adicionar reações",
        manage_messages: "gerenciar mensagens",
        manage_channels: "gerenciar o canal",
        mention_everyone: "mencionar todos",
      } as Record<string, string>)[permission] || permission}`,
      type: "boolean" as const, scope: "guild" as const, path: `tickets.permissions.${scope}.${permission}`, group: "Permissões",
    }))),
  ],
};
