"""Keep release metadata and runtime state generated by tests out of the source."""
from pathlib import Path
import hashlib

import pytest


@pytest.fixture(autouse=True)
def isolated_apk_releases(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    releases = tmp_path / "apk-releases"
    monkeypatch.setenv("CORE_WORKER_APK_DIR", str(releases))
    return releases


@pytest.fixture(autouse=True)
def production_state_is_unchanged():
    root = Path(__file__).resolve().parents[1]
    protected = (root / "android/core-worker-app/releases", root / "data")

    def snapshot():
        return {str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
                for directory in protected for path in directory.rglob("*") if path.is_file()}

    before = snapshot()
    yield
    after = snapshot()
    changed = [name for name in before.keys() | after.keys() if before.get(name) != after.get(name)]
    assert not changed, f"test wrote runtime/release data into production paths: {sorted(changed)}"
