"""Validate the isolated Box64 overlay against actual pinned upstream files."""
import base64
import hashlib
import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import sys
import zlib

import pytest


HELPER = Path(__file__).resolve().parents[1] / "deploy/voicepeak-teto/termux/box64-xputpixel.py"


@pytest.fixture
def patcher():
    spec = importlib.util.spec_from_file_location("voicepeak_xputpixel_patch", HELPER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def source(tmp_path):
    original = tmp_path / "pristine"
    for name, encoded in PINNED_SOURCE_ZLIB_BASE64.items():
        path = original / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(zlib.decompress(base64.b64decode(encoded)))
    (original / ".git").mkdir()
    (original / ".git/config").write_text("private original git metadata\n")
    (original / "x64lib").mkdir()
    (original / "x64lib/lib-test.so.1").write_bytes(b"minimal other copied library")
    (original / "x64lib/lib-test.so").symlink_to("lib-test.so.1")
    (original / "src/wrapped/generated").mkdir()
    (original / "src/wrapped/generated/wrapper.c").write_text("initial generated wrappers\n")
    (original / "src/emu").mkdir()
    (original / "src/emu/x64printer.c").write_text("initial generated ABI printer\n")
    return original


def source_snapshot(source):
    return {str(path.relative_to(source)): path.read_bytes() for path in source.rglob("*") if path.is_file()}


def test_actual_pinned_files_match_recorded_upstream_hashes(patcher, source):
    for name, expected in patcher.PINNED_SHA256.items():
        assert hashlib.sha256((source / name).read_bytes()).hexdigest() == expected


def test_fresh_overlay_keeps_original_and_other_library_unchanged(patcher, source, tmp_path):
    before = source_snapshot(source)
    target = tmp_path / "src-x11fix-1"
    result = patcher.prepare_overlay(source, target)
    assert result["reused"] is False
    assert result["patch_id"] == "voicepeak-xputpixel-1"
    assert source_snapshot(source) == before
    assert not (target / ".git").exists()
    assert (target / "x64lib/lib-test.so.1").read_bytes() == b"minimal other copied library"
    assert (target / "x64lib/lib-test.so").is_symlink()
    manifest = json.loads((target / patcher.MANIFEST_NAME).read_text())
    assert manifest["protected_entries"]["x64lib/lib-test.so.1"]["sha256"]
    assert manifest["build_generated_exclusions"] == ["src/wrapped/generated", "src/emu/x64printer.c", "src/git_head.h"]
    for name, expected in result["patched_sha256"].items():
        assert hashlib.sha256((target / name).read_bytes()).hexdigest() == expected
    header = (target / "src/wrapped/wrappedlibx11_private.h").read_text()
    assert "GOM(XPutPixel, iFEpiiL)" in header
    assert "//GO(XPutPixel," not in header


def test_repeated_overlay_reuses_unchanged_target(patcher, source, tmp_path):
    target = tmp_path / "candidate"
    first = patcher.prepare_overlay(source, target)
    before = source_snapshot(target)
    second = patcher.prepare_overlay(source, target)
    assert second["reused"] is True
    assert second["patched_sha256"] == first["patched_sha256"]
    assert source_snapshot(target) == before


def test_upstream_generated_build_outputs_do_not_block_retry(patcher, source, tmp_path):
    target = tmp_path / "candidate"
    patcher.prepare_overlay(source, target)
    (target / "src/wrapped/generated/wrapper.c").write_text("regenerated by upstream CMake\n")
    (target / "src/wrapped/generated/newtypes.h").write_text("upstream generated native types\n")
    (target / "src/emu/x64printer.c").write_text("regenerated upstream ABI printer\n")
    (target / "src/git_head.h").write_text('#define GITREV ""\n')
    assert patcher.prepare_overlay(source, target)["reused"] is True
    assert (target / "src/wrapped/generated/wrapper.c").read_text() == "regenerated by upstream CMake\n"


@pytest.mark.parametrize("name", [
    "src/wrapped/wrappedlibx11.c", "src/wrapped/wrappedlibx11_private.h",
])
def test_changed_pinned_source_aborts_without_publishing(patcher, source, tmp_path, name):
    (source / name).write_bytes((source / name).read_bytes() + b"user change\n")
    before = source_snapshot(source)
    target = tmp_path / "candidate"
    with pytest.raises(patcher.OverlayError, match="commit fixado"):
        patcher.prepare_overlay(source, target)
    assert not target.exists()
    assert source_snapshot(source) == before


@pytest.mark.parametrize("name", [
    "src/wrapped/wrappedlibx11.c", "src/wrapped/wrappedlibx11_private.h",
    "x64lib/lib-test.so.1", "extra-user-file.c",
])
def test_modified_target_is_preserved_and_refused(patcher, source, tmp_path, name):
    target = tmp_path / "candidate"
    patcher.prepare_overlay(source, target)
    (target / name).write_bytes(b"user modified destination\n")
    before = source_snapshot(target)
    with pytest.raises(patcher.OverlayError, match="alterada"):
        patcher.prepare_overlay(source, target)
    assert source_snapshot(target) == before


def test_existing_unknown_target_is_not_replaced(patcher, source, tmp_path):
    target = tmp_path / "candidate"
    target.mkdir()
    marker = target / "user-source.c"
    marker.write_text("preserve me\n")
    with pytest.raises(patcher.OverlayError, match="manifesto válido"):
        patcher.prepare_overlay(source, target)
    assert marker.read_text() == "preserve me\n"


def test_modified_manifest_is_preserved_and_refused(patcher, source, tmp_path):
    target = tmp_path / "candidate"
    patcher.prepare_overlay(source, target)
    path = target / patcher.MANIFEST_NAME
    path.write_text("{}\n")
    with pytest.raises(patcher.OverlayError, match="manifesto"):
        patcher.prepare_overlay(source, target)
    assert path.read_text() == "{}\n"


@pytest.mark.parametrize("placement", ["same", "inside", "ancestor"])
def test_target_must_be_separate_from_original(patcher, source, tmp_path, placement):
    target = {"same": source, "inside": source / "candidate", "ancestor": tmp_path}[placement]
    before = source_snapshot(source)
    with pytest.raises(patcher.OverlayError, match="separado"):
        patcher.prepare_overlay(source, target)
    assert source_snapshot(source) == before


def test_copy_failure_does_not_publish_partial_target(patcher, source, tmp_path, monkeypatch):
    target = tmp_path / "candidate"

    def fail_copy(original, staging, **kwargs):
        staging.mkdir()
        (staging / "partial-file").write_text("incomplete")
        raise OSError("disk full")

    monkeypatch.setattr(patcher.shutil, "copytree", fail_copy)
    with pytest.raises(OSError, match="disk full"):
        patcher.prepare_overlay(source, target)
    assert not target.exists()
    assert not list(tmp_path.glob(".voicepeak-xputpixel-*"))


def test_concurrent_destination_is_not_overwritten(patcher, source, tmp_path, monkeypatch):
    target = tmp_path / "candidate"
    publish = patcher._publish_new

    def create_destination(staging, destination):
        destination.mkdir()
        publish(staging, destination)

    monkeypatch.setattr(patcher, "_publish_new", create_destination)
    with pytest.raises(patcher.OverlayError, match="apareceu"):
        patcher.prepare_overlay(source, target)
    assert target.is_dir() and list(target.iterdir()) == []
    assert not list(tmp_path.glob(".voicepeak-xputpixel-*"))


def test_cli_reports_overlay_hashes_without_touching_source(source, tmp_path):
    target = tmp_path / "candidate"
    result = subprocess.run(
        [sys.executable, "-I", str(HELPER), "--source", str(source), "--target", str(target)],
        text=True, capture_output=True, timeout=10,
    )
    assert result.returncode == 0, result.stderr
    report = json.loads(result.stdout)
    assert report["manifest_path"] == str(target / ".voicepeak-xputpixel-manifest.json")
    assert report["source_commit"] == "dae0917c47b4edd8956f314210417a20fd225c4b"
    assert len(report["patched_sha256"]) == 2


def test_native_pixel_dispatch_restores_callback_bridge(patcher, tmp_path):
    compiler = shutil.which("gcc")
    if compiler is None:
        pytest.skip("native C compiler unavailable")
    harness = r'''#include <stdint.h>
#include <assert.h>
#define EXPORT
typedef struct { int unused; } x64emu_t;
typedef struct _XImage XImage;
struct _XImage {
    int32_t (*put_pixel)(void*, int32_t, int32_t, uintptr_t);
    uintptr_t stored;
};
static int bridges, unbridges, calls;
static int32_t native_callback(void* image, int32_t x, int32_t y, uintptr_t pixel)
{
    assert(x == 2 && y == 3);
    ((XImage*)image)->stored = pixel;
    ++calls;
    return 17;
}
static int32_t emulated_bridge(void* image, int32_t x, int32_t y, uintptr_t pixel)
{
    assert(!"native Xlib must not dispatch directly to the emulated bridge");
    return -1;
}
static void UnbridgeImageFunc(x64emu_t* emu, XImage* image)
{
    assert(image->put_pixel == emulated_bridge);
    image->put_pixel = native_callback;
    ++unbridges;
}
static void BridgeImageFunc(x64emu_t* emu, XImage* image)
{
    assert(image->put_pixel == native_callback);
    image->put_pixel = emulated_bridge;
    ++bridges;
}
static int32_t native_XPutPixel(void* image, int32_t x, int32_t y, uintptr_t pixel)
{
    return ((XImage*)image)->put_pixel(image, x, y, pixel);
}
static struct { int32_t (*XPutPixel)(void*, int32_t, int32_t, uintptr_t); } api = { native_XPutPixel };
static __typeof__(api)* my = &api;
'''
    harness += patcher.PATCH_BODY.decode()
    harness += r'''int main(void)
{
    XImage image = { emulated_bridge, 0 };
    x64emu_t emu = {0};
    uintptr_t pixel = UINT64_C(0xf123456789abcdef);
    assert(my_XPutPixel(&emu, &image, 2, 3, pixel) == 17);
    assert(image.put_pixel == emulated_bridge);
    assert(image.stored == pixel);
    assert(calls == 1 && bridges == 1 && unbridges == 1);
    return 0;
}
'''
    code = tmp_path / "pixel-dispatch.c"
    binary = tmp_path / "pixel-dispatch"
    code.write_text(harness)
    built = subprocess.run([compiler, "-std=gnu11", "-Wall", "-Wextra", "-Wno-unused-parameter", "-Werror", str(code), "-o", str(binary)], text=True, capture_output=True, timeout=15)
    assert built.returncode == 0, built.stderr
    checked = subprocess.run([str(binary)], text=True, capture_output=True, timeout=5)
    assert checked.returncode == 0, checked.stderr


# Actual open upstream v0.4.0 files, zlib-compressed to keep this offline fixture
# small. The test above independently verifies both immutable SHA-256 values.
# Source: https://github.com/ptitSeb/box64/tree/dae0917c47b4edd8956f314210417a20fd225c4b
PINNED_SOURCE_ZLIB_BASE64 = {
    'src/wrapped/wrappedlibx11.c': (
        'eNrtXetz2za2/+6/AnVmu6JWedhJ0zTapOP4kfWMY+faSePd2zscSoRsNhKpkpQfm8n/fg9eJN6iaMuR2+ZDTBHAwXn+cACCxIMk'
        'HY5nMUb/LMo4yR6dv157IN8aJwP9Xp6kZ/RejEdJilH49vBjeHL08Xh7F4l/j7voBGM0wlE5y3FY4qIMJ9Ewz4rOjwHqPpYIxuPR'
        'MCX06nvrl3k0nWLSefHofF0uifFgdkbu6ZVz9eYgT+IzrN4DcnmUJ1H6mF1dh9M8uYhKrdrV82d4MlPvDaPxeBANPzsIan1nQGKY'
        'pSW+KtUSoPuYkbd3PbmOxskZJbcGBIoSDc+jvIugo6uNjcNogtEr2u3pxsajInv0fL1fmWHr4MPh1rtdqZgojhce7L+hhYzQ2lp5'
        'DerFI5SkJep0T3fzPMv/FaXxGOdB5yJLYtTtIfY36K+Riy6aXIenJ7iU63a4MGUXlT2kkEHnnFxf72z/yNad3o1aS+tILZS6qkns'
        'Ao3tcVbgnaSYjqNriQL8YcJ1UcwKe4S3p5thicBkOC2SLBU1XGJ8SnL8Idu9wGn5Ps+GTAyuNPFHbdTp0tpCbsRbSP9DfcEHEWF/'
        'RBs4OGdNEL7oIZkuOhc1ovwMCFYcQODOhiXobhKd4ZPoAocF+rJGgpUIhFCUXu9OZn16hxEY5hC+WL4TQxzn2bV86wyX8s/pTPlZ'
        'zAbyzyiO+2tfZR5Kk8OrhJRW3NGWnS5jJqRlQWcNSf8YbSSDD7crIE1vXtWLpJhFY6PmTFhCIoqn5blRUatHKo6yfBKVTWpmo1GB'
        'yyZsxlEZNWHyMoktTFoqnuPk7LwRk4OknETTcBrFjWpfA9qHAMjhmCBP93HQX5Ordrrci7gtRdOOCAHB77TMaXXwsHCaXOFxIHUs'
        'wo1TrS6MzsAhzdbO5r2656Avux84ssSvv7l6FfTR48dVc5RjGBFTFKEUX/JAQOU5eEuKcYzosAXjK3r1Gg1nRZlNEB/eNLEgkvxi'
        'CRm+iniyRFrI+/+iEKce1OP+0VecsEj+i8FnERMFhnG53RVz5j7S/kG7dDYZADRBS8pzIfw+SdEpxGqOhyVArk6QhZFBjxA8/fcb'
        '6pQwFvz7fXJFr/7DLgQVEUMkcEwalMo0g66ArzLjEvEgU7gg/hxmeYzzvt6eVifliJb30MHJm70kL8D67/iVQY3F0ixNVMGA2u+z'
        'KC0fESUVwyilwfOihzae99DTTQcZ+KOyBmQa8wDxbEhUd4iT8hxUc/pvkE1XrSBEAbFvVS3DSperqBjRlxtGwyEeR3lUZtQuKQzI'
        'iAOJLgSjQD2qr+FVgaCIORvqcO4DQaIGlxzHkJYWnw09UBLgnf+FUTSP0rMJDLBm87Mc45QR0EoG4xmWCio8zwZ2dyR4nGWficsD'
        'GoA/DX6DmEB5NitB9oJoAhKRM1QHiYhqNKpHVCnCaVLV6V7sTQEFOno2MquBZLZ3IWqo6QovT/am44qEgiwyMYHVB3vTJFGr6/Bs'
        '7SJJDjytVFSWRewShCfNZ7O57XVYrrPjrZ2d3Z1w7+Ph9of9o8OTjsDUX6mm3x51TvchXj+cQwoSF0CCqkyrcZANP++IbJKpXavx'
        'MR2bdeS5zRlOMTg+jh/X8x/I1om8+jSIDwrytKSS5uTj+91jkOHXNej1SUB5gKuN6mqzunpaXT2rrn6orp5XVz9WVy+qq59qyqQT'
        'drVRXW1WV0+rq2fV1Q8g+OPHMNSQyWEWYpLAVgJAhS1GvCijMhlKHgZpsdImHA3L8MGDLZgWPbGBvEyFpLlGe2jb4bnt9FpkzjkW'
        'V7QS4+ULuvk/5gw8BegAQ8HxLN2bpXT425uUHZd8PbQ+nU7Xe4xLwh/jrP/r2tc1bvC1B7OUxMXbIyExkwF0GitE94YllxmoB2t8'
        '9B91viM/BXdw3RcFb3F5CAQv8F467HTqWCT1g0oeXy1GSjUwEHab8xXSKIhebBZk1IUaaE+VKhbuF5z5i8fNVLb6XrbQ1zmMTXMg'
        'NgrH2Vnn4OhteHh0uAuW/hTlKeSAPZRmaJLlGBXjjGZDiE3t1bBBAgR+Tde5njlPhx8PDmBwUL0hh0Z5gUPDI8SaSEmXG0QANPSQ'
        '7XM8/PyGrrnEhNLD15eP2BJMj5IIqlmDcH42JM1r19RvuO1k9ngPLlPO8xmVylYcMy51JmHsmk4prz30pEdVTpJuim6sP+iYMNAQ'
        '3ZQ2LdBNbb966GaV76bophBdKXRzmNOHboYF26Cbs1+Obi43c6Obyday0E3pqSW6GR5xz9DN0LYb3aymvAt0IyuwIV8ebYpucps2'
        '6Ka0t6IbrXLHmGaTimKagDTGVGM4k+mtFpzZ7eeFM91kreDM1a+AM4dfeeDMYGtpcCb31BbOdI+4b3Cma9sDZzZT3iKcOdAsydrg'
        'mdaqBaLpFBRMu1sYcwhDgIzhWGMA0yitFIQ5TeYDMYuV2sCYp28OZG6HckOZjbllgZnWV0s4s/jHPQM0i87dkOYw6u2BmitDuypb'
        'JWlaszZ5mk7ClaqJy2EW44Ku1xIvKUPy+46TOIfUbG4qZ3I9wW3FaOPETutjtXI7p9m96Z3F0q0yPE/vIslz+6Unz7Pxt7RUT+us'
        'bbZncZP7lvBZ1O7J+RyWvc1ZrAskh2SPUMj3izRESKVNC3hU21uxkULM3SKgVSplGsuYaop2Cr2VgjqH/Xw4Z5isDcg5++UI5/Ir'
        'N7yZbC0L25SeWgKb4RH3DNUMbbshzWrK5U9jc3yWFACmYTJpiGVSiwZIJlGhOww0AlYoq7csBhKV20M1E8ksMqmPGIClOOgTAo2Q'
        'TKK3UjhmtZ0PxTRbtcEwR58cweze5MYvnaFloZfUT0vs0nzgniGXpmc3blkMeAfPEk63szRlmwA/ReXwnOyobohftqaNgMyFZ1aC'
        'VmAjW7nonBVlUw3jbgffmuKdTwcU+JIK+RjPhN9FANDWwUohod8LfJDoMncbbJzHBQfJOS7rRksnr8uCTVuH8/ETAvoqGS2yp0tU'
        'XyRwbROrio59vYkUWZKR201KrFMuM2Z1kdUEhbO6SIwKgisVl6ZhfbEom69N/Nl64zFn8TB3nCl8LCu2RCeN4ul0n2xUT6PxVnGd'
        'Dv+10Hqute2ikeYJOjt9x9ajaqAczEZs7BzjVB5Qg6UEY8sg9aqORWwi7VsC4ahYVCQqzAJDrK2r1Rpj/X7kHWRdLtJqlJ3Hhxhm'
        '5/i9Z5x1sru0gdbW43xkoNBwAi3O8yxN/osXyZu1Zk0AwYh8nQYJ+qBZ3H1ZRgQ7VjZdsoJl1hsvZ+pEVis2ndb0hqXFfq0i0tO7'
        'CEa3u3ni0Mbf0kJQ66zlOoHNTe7ZYoFN7e4VA5dl72LZQHrppinsSU3mQZ65NCA3NnbqLAXmnFN+ixzyTh3UPPGQKK0WpllN5cUz'
        'zT6tsMzRq8Axu/94MEznaWn4JXXUbE6hvJDWNH6URv4IMuNHbTw/gpYYP1Y5lAhqGj8KpdWKIIexvDFk2KhVFDl7FnHk8iNPJJmc'
        'LS2WlK4aztDpi84j7mbitf2C7jGQvl3RdIuB1OQGc/XFJvTV11OU3uswjarJe/0eLRqyaXzM/lTvFo2kKmfS9Tmrl7A/vwV3ONlv'
        'Po1gOYlli4TFKnQZYJYk0xn8B+ABSgL1gFZAIyTV6hHxidQ9kLbv46AR3Kg8rNa2CqvPendVaH7WalOFo1exp8IeSJ4tFTpPS9tR'
        'IXXUdkOF7gv3bUOFpmvPfgqLGReeYWzNymxC1Gifakz36kC2zDgAyJUv1zREcqVNi81iansJjIPlL7A0WVyxyscTqWiRiYhGaaWg'
        'zWFEH7YZdmsDbs5+Obq5nMsNbyZby8I3paeWAGe6xD1DOEPdboiz2vK2Mc7+tgBAW/WVrYawVtVvkZ3WFNMiOUtxjMZZeqZSVbJO'
        'AoUD9mcYLHc92Q59CqMWEDS0QQBQTgebzyclWisFgRaD++BPsWQb6LP2x2HP5nxuyFNZWRbcVb20hDrV7PcM5hQVuyHOsNttwxv9'
        '/pQd4KoPATYEuKr+ggCn5281HSek9VQclLemLHFPiiOfM+RmUHagTG0XyutqiisFaBYD+wBNsWMbQLP2xwHN5mxuQFNZWRagVb20'
        'BDTV7PcM0BQVuwHNsNsS8jWIPTuiVR8VbYhoVf2bpGzVGmFNzY1r9bJfLF2zb6guO2VzreEZWmD4Npvpa3cLpGw1zZVCOIvBfQin'
        'WLQNwln74whncz43wqmsLAvh6q/ytkM41ez3DOEUFbsRzrDbElbdSPTZIa76zHFDiKvqN4Q4PVmr2yugRtOyQfDtF9sM+Qh4jTly'
        'LZSU1ZRWCrIsBvRBlmKvNpBl7Y9Dls2Z3JClsrIsyKp6aQlZqtnvGWQpKnZDlmG3JSRlYzte4TQmH73WHgYXlbHo4+CI7PFc8KMc'
        'Spub5G8C6BR69ke8/E306vkuf4siWOayW2MgtOlD2pGtZ3ILAKNCebXA0e4EXoDU7dwKJF39CqB0OKcHLA22lgaYck/NdlQf4yKb'
        '5UO8NR5nw/oz58oazen+Tr9h6CrkFnkACH2Y7ZtsO1xWTgIMWULRKl+bnVQKoZUKPIcJfYFnWK1N4Dn75YHnci134JlsLSvwlJ4a'
        'BB7vlPKxJh3ktE2f/NMB1X2Gk7i+SAp50YEcQlGf7TSa1EcCkBNI1mwer77cW5G6NLYw0ctpFNc/BtMxOVVAOcIpTUoP68mEHtFU'
        'CwvuOVdScggLES6PLqPBGNf9X9WX1w7ZXPJU19NxlGJFZbpI72ctWORnRQ1rwcmylZ1H0VmRD8Mr9ad0UFdclHIp+bmY0IbiT2aD'
        'RQWbI8ENDMI7Ms3hdVqqVr+OhNhU6h32yNnroeTMI3JWRjIi4fl+63Dn6HhL0txBFsX/M8P59V7mPquMX6TRhBB7AGlyMjIOKznd'
        'f9fwKDVaebtJZX7S0Rf5WLNxQt7tpAex0Nu83wqj2IEq77arnwtS27ZQ25aoCaQ/PXyLswku82tRSM4AUe+sS7W5terKsXpDrvs+'
        'xzhOypMyysu6wdRy19JqJ0ux0Ui+aWsDIWG2kW5a2mxHMAgYjZS7dplKfJiVyejaJpleJlMgxbNCU0ph3jTbqCopjHuWFopCCuOe'
        '3OL4eaUR0SDXb6k9kEM4t7OUTOohE5P7sZes08x2VibjpLyuJ6bSkTLFbIrzjSdP6FkyZEOz4Z1NXxEwGi76moBJwDtBDW4737W8'
        'LuCUqXpvv1qBa/7mjUG0UdLLMibpyMUqBe5MQcPePLgiMvW8NeCxn/fNAavZWr094OVAvEHgczPPWwR2Lpf2JoGJ8Y3eJtDBvnHs'
        'ae08oWeJO73xnLBb4us5LjmMcGscaxrBFQk1p7n8kWYxVLtA8/RfxZnbpXxhZmNxeVGm50bNgsyWJTWONFvjhUc6K5G7Gu38EeiT'
        '70ajno3wioSj36b+mHSZsl1gzuOkis45bugLUSfHy4tT67xkoWCVs+5FY1Vuu9jIaCOw9NGxUXzaZGo/SlqIrlZo2k3YKDJ1490o'
        'MF186HHpcLkGYWmwu/SoVCa5iwWlNLFdOCiltu2CUiawIkFpkenmQSkRXbGgtJqwWVBqxrtZUDr4MILS7nJNglJnd/lBKa8jLRSU'
        'ykLaolGpNG6b1qpEViqttcp3G2mtQni1wtRh00ZxapjyRoHq5ESPVJcbNghVk+Olx6q6oL3oHFRfuW4xE9VJ+ALXOxs1CM0L3mW8'
        'qOKflbpkNYO4xcxUJ75y81O3pZvOUm0mvulc1ceVZcbqcddm81arDHcxezWeQDULdssDqMZRbmk7ZzeRJcJtROaPy3cyMHvks43L'
        'zaPaQnhFwtlrUn8cOwzZLoDn8FFFrt8FfSHrYnd5sWp71rtIkLZaZzKbLjgCWwjczcg7Ly4bLTMtGpMruMzks2CTiLydRSY/F1o8'
        'tlhicvC67GhsscBkbqZYNBibLS95gnGB5aW7CsYmy0sLB+PqLS/5LNgoGG9lccnPhR6Miy8tOXhdejAuvrBk7FNqHItGS2/qaolF'
        'k8DctHXZseiUyZKuNo5Fg+iKhKLHgP5ItBquXSB6eaji0OdqvjC0M7q8KDQ3/TUdEe1b/BYYF+0EFl7ldRK6y5XeeeOlX9Ybrfi6'
        'iK/M6DnPzvPGULd5246k8zmSxtO5buofVT3cL3NsdWzNXfQNGKFBzqPD70G/5hbDwFpL2yIV2GnZNmgErlpyPh84acmJhruWsnYe'
        'ePjSl94CqZZl0m/p0ZyMBMhZy8G8qGWgeICstOxeEdR2/mUr3N46OOjsfTzc7qG9/eOTD+HW8dseOuxBGVyd/KeHjndPPh58qM9I'
        'Ki6TcniOOrxCsDhw3nwH5zAqMNp8eVPwppJBTBP5O5L4Z7j8ZSs/Kzr0hRJQxgVA9ZPAUbARiBeyFeqDHEef+zeS8NkKSWgt2HQV'
        'PFV1cnONeLT0/CVCtz+wf0vNWQueuQp+kHW9HE17tP/iJVr2v3tpEWvBc1fBj7UN786CHqtuPHmJ0Lfo/U9haWvBC1fBT98mvtt4'
        'zeZLhFaJq7+8yepNDgndssspzmp64DzPfPYSofvA7V8ee3seay9xSr/x9N56+Tzvf/4SofssxV9R8W2jwl7ilH/jhz9cJM2LsBcv'
        'EfojSvdX5N2/yLOXODWw8eOfJlrnrSg+eYnQn0nqv6L7zxHd9hKnDjZ++tMjgjtmYjyKZuPy5beJVvtDwkv2kPAl+lvx9wJMSD7l'
        'hTp/iwOUFKjMMjSOcvKVrhTjmB8CCNeX9AEhItD33a/peg+FIflKTxhWT3/ERpJv5QG/0meU2h6D2yGcjFBHdf4N5vxJgL7/nnx2'
        'aziZdjrD8yjvBo6KPQQM8efHtaKkL291UZYnZ0lKnhvLtx0E/7ER9F2GLxwtesoT6SSNHzzYevCAbAdgXQeOA0CpandP3x8df6gP'
        'WDj9JWLfPjzERYnjg6QwPq9GPoU2S2cF5scr0I67wE3Av1FGKqR0Pwf9eXmejLFD1cAcSv/xahP112hd8lS7Q49qZftBEvRPlJI/'
        '/3gFwwinrz9E/7om7WjIcQFN630O4gnn5Prha4twvUoU4Cjtkebqg3K40bcqin8ictv+9bmrZHJ72rkb5QiBeoz5RfVxgsv97V+i'
        '8QwXLpUM75tKJJl6jH+/VurtHHb9vPPr5/ZdZjnIybYMLQs9GYK+syPou5sg6HJQlLnUDbxR3Qi0iG++q31TiVi3a3IS2rYfm7Pu'
        '5nmW/4t9wlp32FO5EPHvXIs9Z4L3EngXnCrEiHYxuSG+kE20LIjoccVOEDCqA5P08ACoF7jx6MgrhFrcRAyNIBEkyRYUxdJgvjC7'
        'Qofu78SOI+lDtfiqxCnZ8yNqzBOu7qCiJdGgFoOfCxrN0qKZqNvjrMA7jJFlSqz04xJ8SCqFvHS+1EZ1l8jKJ5tHuxfY/SVbfgjC'
        'RQ/RapXHihqQ21c7PjlVSVJBnJxKcMFkukpGmNyj4gAOEwKaNKWLV3qUxlIZVnq4Ja7fY7xcpuUO2vBMdzjXBx9d5tF0KoEW6lJe'
        '613Vo3QofXKYcdjpGgRgNBNfK+ZMSxcz44p8dZmxwk4hoV9pJhucdUb4aSNd8jVxrhR2UglRa3EN+fUENANVH74eZmkJMfXwNbtt'
        'SU166FMg8orJ2cPXo0d0o+2nBw+AIxFYdEAO5YgSdQNOEkjJR7arh6sHoopy5DE9V6Uqqo4K5Yd6VgXVkXvicLyqpFJ4dahUVVQd'
        'CcMOb9F3/Aqbf0wHC6uamjSA0r5dl/PTN0PN9BySWsd/DN0uGE9cu7wzepMoqPodQCV5+zwoCcpHaafLYqwbdI7D4519iPNuh0cU'
        'u3diubdzSu/NlJvbtpsvxFijByWVocMcpBuwL/vTJd1wd+v0lZTRQhFFGec89p4cdQAW4kssVUxUo4YkCOeZcMuZpMwBUz3eM3QI'
        'dyl9doSCeF2CRpnglmM01R75/fgxRzlE1s2i4RAXRf1h60ePHrmtVBtHJupIB+af4CAUQaYb8lhftaz7u02mtRF2tQ+R8DhLxS7j'
        'rGYJWLmuvIORZOdRfGv/EG9ASd5BGr8v88Kc2VA8QNKAQYS2tax79TDlyKj+KGdycBWZ47COruxUCiX/q7K/mcOfiKh8DONycP45'
        '35Rf5nA3D1crryJynXH7JzmDRKDBIna2I0elsGbgUTmAbPIaUQjt778nofbdK9Z3JaonJts5gQNTGp/J0kaHVGtKB6L0q3HIyRWY'
        'jB2eVvDlMktBN4XZRBWHMOkRE/KO1UfY7OcWi6BTTxtrSSBnjezYlq+STCCNCfM7+PctUupYvuIvtg7khEpFe50AfX90H+ZieRqN'
        '5RKS7w8HAUuNPMsyn5Icf8h8c2hjVYbUDdPZZIBzUWlKTtCxrMqwdU7hrfIyjdxvvUqjkCayXUK1sMzCar5NewpqmvIyjVFZX6ax'
        'r8GR2h8ywtCdakDu16MBdgekItLN04BR2bNQRRVwjM8SmMDn++/206KM0jKBfFusx885hCmu/DTHRUiOZJJ/D8dRUfhdunrLFjTi'
        'ZwT6jKkUoh+pB6KknLeGiaHb8YXMH9N8VaSex4pPbmFzTXZhcb8O6EFbu2JRdI7f0wc+iDEABCB0ot+ynF+PkhzGPup46h2yTCyt'
        'rcnur/VedcS64NQVwjLNOm8nJGGYJc3I3+/4EypGZv3twek6fXD15uj0+bPdw186VxsbZ+OrQH5sA5nZOXmruszIo54hRtCK/Bhg'
        'mqZNSxyzqCRPx9IMshgwAbAkExjjUcm4RgC+nNfTU0qHbywRKV6NAxt96VGRc62TGmsrjrezNMU0W/wUlcPzRgYbzfM+C92KBB1Y'
        'tFJyHBlxsZFrWOGQMsku8K0xzNHBRvNmzFaPlLZGED3igw9zGOVfY6iSJg1/T09gBD7PsxQyXsGACEjxwEntTpXB0nwUBC7W68rz'
        'By6UpdlopHlBc7alriqqjCJjjqd0hK29HNP0sVCOt4vKbFLIGdMki5NRgvNJNJVvf8bX4YA8g0vPlOp8wTmMB0raxaJre3tbrUzP'
        '0tsG0sptUANBnPL6nV4wCUfJGMyi3L36DH197SvCUdCS4MMokhJZmfkYF32OFqTiNrmhV2JLsW+3RUW2+PV2+wPk0wbB6TWrSerB'
        'D2ut0XhWnNNqUGuP/LBXA4NVxIj17F0y9sjhjH2JPfLbRZPXreg66ipP1yrhpcd4ljZ0JBB16UNOV6WQnWTXryqyTygo1Qn8gOVg'
        '2OhbSVzQR/KUxHuyVc/V4QDDGIJDqnda+w29QVWvVLe7DW+o+5yS3qtTKLPYPZFSz7ekiEuRoT7r0pjOqHwcZMPPZIFJimugP4a7'
        'wniBdKJ0X640S81qqMuqab3UML6fjjJpt8wo7ivZdRSH1dGY3BFqZdRUCJ7J0ABNpEM22c3uJRkxpNtufrh+LUzTUUfimQdC2udh'
        'bxmffMd/cuo6bal/bZ5N5/xMwWGx9kVxTdSl2FkR12SsIbtLA5esTBV1TVn74jfgcRoOyUNdnKslMD+BCQhNh0L+lRJrhSS1VWCh'
        'CPlWnEl0yQnmOT8HOhxEBXYUTaLis6Mo0QSoCorzZFSqjTrdqjQip05zvw5UCoNrwMMsj3UFDJISRp5wlialtWAaxdb78MdGDqwO'
        'g2RZ9DWLTpMr0oqVqk0u2ARSF3iMFc0xMueYPC/pllEyVuv/PsaSXdRT62EGUsLE43dARfJXFkityOvo9hXt9fuD2Wgk813dnZa2'
        'u5PoytIx3K14I0uPOqZ3RQ5RgySBThUoA707jl2hOkqQ5jwJCQsYIrHm6ym7aRjPuK2qbZIRnAh1dVxk46gkGwXV2qNxdKaFK0RX'
        'CKkUSTy0AlCOUcB4gtvF9cRg1UjUBClePyQ7EgySTGlXXDeFXgDyU8jVJVQFE7XAE8/Kc7V3Ami6m5vDKqlFFkwK3eJspeQCD/93'
        'Y/PF/4kRqYfUv4HejC4xLdCKoAkd+iY4Ipv5dV8kZVb+tVGdrSlyF3W6zSA5A8fXnN42grNRe2T4ZaebxOME4kaCPVk+UEKgi2Bm'
        '7ELw4SwvAONHJA3UY1CaDyhyUB8FTwrZF6kcNcDwoao6+yyhNlyXZ3LYedK3pq8va/oqsDnb0NJYbdKhlEKQ/JIUs2i8b05C6DoA'
        'GuqhZ85L6pLfyTjtcgOaSzIHL3CeRGMSKL4ooXknLqxV9PyH8BSHCVyrKmb39Uh15khdmkDQvEsRj5Did8NhNjM9BxSCY2zEcxFd'
        '4NiAcSMWpUzhSiVxNZwkxTDMpiY0grvCXFCTmReUeZQWIRHGbDMcuNyXGGiYZZ8TrMtxhlMw2TC04ZPbZ21t6RyxKQGmLMbSb1He'
        'eNwPZ2QHztNNyF3ohOf5M7gqUJaOr/0ZgdIQuZrKk7DynHRoRAK+grSJG91XFopHNHKerD2kYesqR1Oc+jeqOjegyk3j+tnvVhyD'
        '+NEMMI9++5M/Cx7gYTQrMMpGqDzPChibh3kGU+dsgk7HCWBq+eickxC7wQiC1x0I649QB349fC1QPQBnUG7wq2r+FQca3Y90gqZR'
        'bkJXn9kBZb5sJ2mZzgjJriv1bkDXO6XFXGMTBq0gasjLuCTSA/qBT211ClqQ11b7+jt1+4d7Rz20vpflQxioEGnCWsQom0KWAfgG'
        'roc4c+hvU/ruHH1s8vUWdkKKFyw6oIiHr8V7G/UrDEQBdIsse/wbdxi1HuL1A6ku+QcetSXciTWpWnwSjXroSQ892KJfH9OY2iRc'
        'vZG3aArOyHo5u3r4+k2wAIukehsuoR1j9A1aD9crfvmmwM1OPSHtsUVEiMJ6C6JaLqWqykZFtZacsHiI1bmEp5KUEvhI1amBp5ay'
        'POmrV2UFnkowYCmlHXVGSzds1psy63FT0tvjxx+Odo5eoiqH/lm9LUYo9bbIkNW7av76c8WyAJIekmGEcd631FLhRq3XkXNXWjRN'
        'NElEDqgyx9Mf5V6d5qh1lbSl0p+WfFiUaIzrP3uKxdD9M48D7ZPI4tfmWpNtfHQ/0DEbdfXxzERptnPnRVgisrxU7d2BvE4MejCe'
        '0XUfMjxEktD0PeQCzaYw0AKq0s25EGJzlisR+UY1RQLbFIe+FteZyg/sAIZcn7SePnwtsr/vXkk/1FyeCMBYFSzSp3ZkdGYY/92a'
        'sQGEvFctWCO7g8m+aoVfur9a6rI/DwfZ45WHry8fsU6pywA3057cF0XGdaWndY123SkwJjWVphbVFdE11K+XiL+u6Q8FFW+h/sD8'
        'gDiA7F7qp+DZs4BPoJbssqmPsdYXm/W+ioun0vUzaQ/ZxQ/yj+fyjx+lJi/kgp+q/c0bT5QONzbqkk3h1NQDVYjkdj7mN7fIPWJl'
        'S1VukroT+cUXWTVUeCIyEZWISCQjAhE5CP+UbcIwYxMYbLZVlySe+++aqJ6LvlldPa2unnnzWiCvsc95+wNkRr7xUXuN0/+ovsFb'
        'btNrx64I9c216bW60SGAsa/a6gFTSzEGSjU11oSmtz+efDh6Bxnw/gfHmyMWnWngBIMpeYWBvxERj4vriahCnxKvs8WldzOwOIzU'
        '6wFDLv1u/zY7ZHMWs0v9fr/OceUpBJ9PggNVu+w/sFsdsrtKaO9wd3dndyc82H9zgtaha1D9oyJ7tLEOVZJ0OJ7FGK2zN1Eg/SCr'
        'BAlM29bX/h8pwMWn'
    ),
    'src/wrapped/wrappedlibx11_private.h': (
        'eNqVXVtzKzeOfs+v8NZUTeVMpSaTna1Uat9sWXZUaVmOJR975sXVliiL61Z3py+yPb9+CYIXgJf2yXmYjPGBbF5AEARB6C9yf/Zf'
        '3+/EXtZi9/316svZX/965v9cBn//N/v78nxz/uXLd38RXdd0Z0tx+Pvf/67+qndy/913AF58//THvhPih7P/+XL2449nD2VXy/rl'
        'f8/2pazE7mxozrZNvZfd8bvvrlffP55vB3kqB7HeqkL1ujyJ7oczedV+UehSwbvdrKlrobia+qEctgdA522rGTQ+fx9E3Sv4h7P2'
        'ypN/bfpB18RJPdKkI97Kd1H9cHa6aitH2zSu0kJG1WwaaOZaIL0w9KpqtrOq7PtfZT1AU04UaKoG+1W0IXkmqgpbVch2bMcQv63K'
        'WjgGqf753gPTQo3nWv5H+G8+GeDyh7PCjIgj9bqrrv9AvCmPYkdb2LIyamZw3FveWfgm9LUPO7seynpXdljlsWyjhm3EsY2qe1im'
        'Knubn0RtJk16djsmha+4/6i3c5DKX9XXKyNFqqN2qMahuROtKIfVfu8kjNFrQr4oe3HV1AOMDYjAag9/6Tl3QnahJg4bZv6Wg+qt'
        '+t9VtyNSbIHbchfR7ms5UGJVbl+NQBa+Xkdd7XGZ+Hl91NLj6a6q2aGsX4ReXeK2USMruuuufNYcY1FQpusZjlXBiv4mPp4bPYv1'
        '0DUVE17OsSzVMNcvOBTSthp5zKdpJSDBnKdrWtENH/iJogjrYKuNIQ+y3jVv58PQyedxsIuksMpjdhDb18Vei5BVG64HClqW/asD'
        '24pCm49W7DwmIww/7TkKxhKhrnLZbccK9N34/KaZet6vGL9s3mqqaRIs9y1jqETZnXeiNDXLcZQEwbbxArK9aN69moOxq5peXMq+'
        'rcoPHDvLq+iLpZG0H3/Ui08TCyVGnmUVsGyPPehyJfN3YqsYgaw+Y8igKdZtuRX0U4hdjbVW/lYCPBYq1oJDCbVWsOZ02w0IEUwR'
        'ac5sNlvtqeqa22IGX8yL8hmGDFeTEqpxbNMcxacMvA7YQCkHGZaf/9Yrfdvsvz81cve3L1Cd5n7y7E9tp3bpd94bjfw+iu5jWb7P'
        '8GO7XaI5lqf4Fh5bEZvfkOfu+iLbFllPfWfTqP8+/uvfdtGOMcvDQaoVcJD7QY9Sb1mLNh7r8fTJZBiG8fQZC+dg06UY/sx0jafc'
        'dI2nz6fL8xTfwpOdLsqTmi6LT03XeNLTNZ7+lZ2u8TQ9XXQgVT1/ZiAVe2YgFaIb5qc1aphlmRA1zbIRr79+nQUsrAlfy0ru1q1W'
        'bbQ37x+TvQELue2a5/K5+jirhbKP++Yozt463FLDzqraMp1VSKIntCUK+TPjqtgzn1IIjqvTXdGgWZYJmbAsquGTLEoqpV1zofhC'
        'G+nAk9KVVHpdC522QJRGn81QmbOPNLU6b3CRHAv+GcryIIcDVmr3DMvUfpit7bzeXenjTwAv1quiHGT9U9G8iU7sIgZjKZ13HWy4'
        'DOzV0Yt3T23ug3BdggOBtmxIofFZ3DXNYMVREy8vvQT0CRHIcC60kZoQGPsx4GYDSZp6KfblWA2+raygqITqhzMKSAMW39zUxZ9q'
        '6mKiqWjtRLKCJed/jGVlJr83lo4iX4GdoOTr1qyVwh1dAVSSoCs7cUsI6ItanzAHpXzbnk04oFlpuBbDvBJHb7U4Mq0wxLyJTegw'
        'WH56+ghTZ4p6Ue8bqtIKJYplpxYlM8v++Zla6wO9ZgavaJrXsZ2w0Qr1pSfbFtNWP/Y45nA0gzmAKWOFb8f+kBhHnBq9r+mTFa77'
        'gikGg47Cg+abGklbnR4yNr3SJVGl1/aclvzkndhlMS17HvUr4E68TC8WPySKNRRYhvZNdRKmdxlgrQ5bcNjzMqHmaHJnoYzym/cg'
        'YE7tQEAPtjpurSGDtmYIyirO1Dux20ChoVEnHTM2vrr1bAZrQa2DPl4IaT7UUv9MTRO2BU/zN+PxWXRGHclg60KWT3c49bnUgSbi'
        'aY5qSHpweClVsUUuvqMormsxxLJB6FydKkA373z3f2M/xNVyLt0JM/Tss37vMwSlhzu7t5mVtx6aTsQ+Noa4NcmqR8vuCd0BzU7u'
        'uZZAGCz/Wfpo4Bm+fsowS54dDMO3LgvT4IQAIzJ9duA8X7+FJ3l2CHnCs0OAr8tjW4ne1jTmPifrqSZNmpTI8o3HjPuby/nV4mZ+'
        '+cmw2+7e112sGvG7X2Wv7IKUzaB5tdJA/WG9I+D9fhk7Qf0wo/WuOF83Lv7AzYLo44zUNYh3tYm3ot4pk+CyK9+sJ+4L5VBNTGLa'
        'Eip7ARZK0XL6WhlnuinWL+e8hspa9e6lotUOJukxq2ucKVxYT9OTxrVbbKa2fimMk9aXjXyRYBmDs5d/rCBj0n5smvPuxQ6JNo3R'
        'u3rVNcfLciixBWrdfSEsXiNqUFIMfL2zsethrhU6hpj1AxN/osauZ+jWLji1+mgPpLqiUBrA+dk0y8IIz9cvZ/BPmU9jL85OZVd2'
        'L4zvWL4Io0bVMLRu4Hfj8fjxFHIRJlPt0JwdypM4Gw7GGhOdvbYxhZejEpinvZr1YDn4Dq1mrvf8n/2K7AH/Sorcync31iOfCITY'
        '+LRtigWmEyeWTaoaTsqrTBxzF3Si5LUEFWTXXGH8osYT7sbX43PDIEdnbcEY7cTz+JIcGmtJU7GSSSjhxTccaiEPB3qlQOmxk//J'
        '4vreg95SGbqRRxkQfU1tWNNi5etKIvN3sF1OV2SXNgwrpYTAMZwggzOYNgF2bzIVrHnRTQajr/bOJ92GDMYwdRNv6KihEwNhVXd2'
        'MB5kJ8jQ+s8pm8TKq9ZKFtCnWdS4zKuPiLYvpAARmNdDh12YMZbgKsQ15w8ccqM0NEVfeLm7rhPaTVhTP3TNx8IeO7V4WyJqBm1M'
        'wkrVLielE8b6uZO7F0ErWPkKHM0uLhnQw9sMBsYXDpdqYPXWoral/N6lZlodIMX5Vp1qenqD5GAQBH99Khn9VyFfDkMWWC4T0G/i'
        'Y9vszD1Sy7+zbKDBF+N+Lzq8bi2ClsCFAxVL606ARRFTV0lqKIsWIZfAvMle6nmBB7kLVAmhB51vRH+hDsKqHm0u0zFWEFy/3asp'
        'Mha0AdRsnXdbY1NTC8Ag1txuCVlLn22wKZjBf/o5yVFIawm0/hbRAv6TBHDnCl0koCdL3CnRLOuXSpDOJdBUB9fi5ShotQTKd3uy'
        'xxunSxJAXObpcV4OuD2evNVlaA9Nt+stoLX04/xXUe5W+yDcQX9kfmyHeMHP64k1qb5U/2F3B80NTjNSh2OjG5bdWzXR+pWiPdaY'
        '3HNle12IvRLTq2rsD9YBatQcoPzm0sKkeGSDZniuZ2nImYETMC3rINPrRCGN+KUcloPGbhrYjpKl9UhkWgsWeLatAGbK3aq2YLO+'
        'ltUo+iQTtGjTBN0KUbwEz5dOzYSWHQDgit5rxcrLmQ4LUafGET1mdmWk6O74LACEE9lR1YpSbmqyg0vUvl4SO7FT59c78YcagQG1'
        'fnVFGYY+jAwx1s/VLz9fyJe9guwMLIWa321vv6sYiqbc6YNv0WzLykyTboL5xJUYtgfcctDilpT+MeC0uFWlydHpihTBHYp4SK5k'
        'VaXVuEFCVQbk26b6eLHHQtCdBMsrT4Ymqh1ER+IlLLnecXuq9cCqDrSWM/DUSKBucOaL+Vuyv69nRFU9Wdqs3B4E1WEwLXSWiYxc'
        'Nd02ilyzXdJHX3p8B8r50Bw3oEGNktU3BO7IQHpu6XakJAWI7enVJyBG7Sl5ek0d4UhDvPkwboexE04sFUZEqKeDaCG3v7ihA+Td'
        '0CXjj+LoPOblndPwzoFE6VkAxLdPVHJbDocEWc/WiVVv3QueQoxyUwUdz8nDsL6nMedaPnOoybHLpys6Shj6Bo0i7JuD2jN2umcn'
        'NkmPP/30OLsI5ujx2iwJOA9Dh5wdei2ao9AHCx2y1MLxVbY+nO9aDPrU4OfPW1EevRNt9WEP+G5xA6pk19m4RUS2kZVe4BWozuv9'
        'rehMTJstQuIkiTLSbuTjUR1prHZwdHf10/rFd222TejNc9kLZynpdnMeh0mKeFn2MqHoXqTaiMzOZx67ntldkjqvAKBTUlg3iRtw'
        'iEitrVL2LYOQzkhXGzrsQn00QIuZ36YDf0zgTuohYlfvwVDM+5O0u6OQzgHVCSVy9VlZnz1qrrM3ORzO1D5VPauzQn82HMrB3O2x'
        'az2odRk1JuHX6h173Y5qdLcjP3cpJBWDGKMu/lAfp5n4FW5YbCG73mmhLx4E09OGnGpPHhn9G9DS1a/k3OCgVWb40x1e0fFxJhFc'
        '09rQz3mrXXaquD6hm+O5GWLj66P8rfQTp2xj5t4zH01EYtKhNjCN5USBXOJIGhsIZWXmV7+9/DvqW2yUyoJOwXpb1pU6nenwV1sq'
        '3DNZU5zjefVWi464jzXoo47p9SsgUdixZ8DhXY/PscC3RMOBmgiWuK9/05VqJ1OioXb9lO5CdxJuXi2Ek5J1ng5U9WW/DQ+8Q1Ul'
        'Cz5yD0sMfFkqG8aflClsxuaBOmtYBS4Im/T8YZlTSA/LDDVaKhRV/RiabVOlsHB+STP+3TRHvvrsVv1SNc9l9VQ1cJuf2Kkh8vli'
        'HAZjtMK0wyVC4VGlS1AHK8gJBNK1jrGhtJKUMUvGQLpCgq5F598y2Ibiadtaado+SDTXeqgSYd0IBYCtXf70S50fBJhDuWfeOLPA'
        'H9Mx0nqtwCmDxrObhS2Ps2foBr4MIFS4SLV3Gk73chi2XDxLBcBiprRzgrzX5yO4QYYrah18EHJsDqWcYlgma9b16u1nPXxUHFeW'
        'iBxmZrvzyGIJd+WyEhATMSrz33hMSEF9SUdJ26FXNtJzH9HGYf9LRHzbMsZLAS7Jxex8s7lbXNxv5glwOQFiH2egW3LgMgbRW7x0'
        'pmfYSzv3GMrg6fN6orUGXE6AmdZSMGqt8T8EhHjqFOCfCnkinj0fSjmYRUAgPDYSQtO9KW0QMxJ66sN4nAOJMgFVDNH6cKH25VxR'
        'vfXkGLQJbjYOePLDkNmhVFs+F30gj12nmppaogRdJlFTCA1njixzCDo4Eg1ZfszrnSzrgEwXl38vkEEvPn4fyy4cE/IEw7h7HLqY'
        'rfaPi5kZLOMcUuTjum268Hsg4RKcmPjNcP6KbWp1G2q4vg05WOF6cPw9cACgeEZkZvMnsGUGWyx5eKohL58xFs9Fd3E4vNsz5PVE'
        'I9YTjbhX4zL5vYdtHgb68gJPdCH9fnP1Sxp5mIX0ZfkqUNMsLkP1prElw/SOqLZkvKqnO2E8OLdl1xsngJo+NtqwSUUKC4hrf/Rm'
        'wNCkREMDzHUZYPE8a3J+njWc6AqQp+ZLM+TnC2HqCfbYnSh3/O8XNdais5sLF3uLxgvCIovlou7VKUCt10GkVKVlRNssX9Gmky8v'
        'olPGX5+pZlJl34luoq09LIxPG9q3SYHAlpv9mQNTSn09qdTtFQM421OtUTgYrrwjeu0bv0wfAaG5pYk5k2md3VS0EknVtZyqa5mt'
        'S5lm3XQ7NMdU7UaLJnt+GIedfq1HaGoWw79TYwwGrHtbF5AT6x/osXABNV74QI0XtrYpoCXp1YZwU+8j4oS9hHhoNFnrRXS12udc'
        'hBvffDVTYvvV9FBRGOKUttAsD50OmaZUvbBvmsFHemoAIvxyS/a+/mYF46vJqZioSY/hID/qpuvbHei3uSwIYC0qGbIyRtV/60AR'
        'P9oZDU8nCKhR3OYwtF7rOrR9ENVu2zBsMcHkfZ0J8FaI7ny3S5Rc9HrFxQCI9Gy1WaPLI8ZDofHUU0xWC3vVGql0MmkgdaBWiuFm'
        'vvkZLqf76HCd5f8T7GjqfTv/Znb7J7jvbxaPafZgGGLp9OSTGRrwNOinI9N3TdpeUmw8PYO3mwBbYFzYEjlpcJJxPDoytP52sAG9'
        'rBLYpT+OlxfkjK6oLuQM/uAXLEjtRTdMRmTppV5Vqdu5WJmh3HMHNnLB9Yj2YbYyJNsbE0kL9KpCGjFhvYg8Ms9NxGo6agKL9plL'
        '4ddnteYuxUmqnU7snOvSXtlqGG4wTNizDigNoMum2cE6a/2VlsO0U8351yn5vJJlz25zHLoah0r7Ln28nseUSrWxf0UGtB9N1IwM'
        'd+D9aq+c39fh3r2aapcrFtDXdjdr0UEYwoeyFXGDVSshjUBcCtOIoBO3Nd5KDjZHtd1lQe3dR8HiEE6zneMxKOhmmcWYERDnOYe6'
        'K642guxsi1xZWL8ZyMhCFnYz/gnHnfV1ZzlyMAkTS4BKYHLYxCeNxEyPqGHKwiBWKXBR7+S2HJpuaS9kGOz92S5M1iD+CncMxBFN'
        'mYTEtepw4sRx01gf+qxlHF9lB+8PlK7FpB3mI47JpVEpZEFpNLeGA7AKKsuSrlWEMUZtxxeDb7fLXgI+xTv4/zZ1CeewPQ6rJ5fd'
        'AQJLul/t3WWCHAmHGqhxEPP9XuikLInakUNJzkUz1rs+DRvBoCwhB8gGwVPwpmltWbNpAt5+QEwBmEg26MgVbT+cyuKfdADPrPT6'
        'jJNEZtffnlCQTjPl0CE+uDiVQeu1usMh9iZMwWPIwaclUbDalvX69QTizjCvXpNYU6uiPLLDoVbcooJUXiOQqt7TVRu0leneE921'
        'LIq6N1kt1b3pqlF3pjGvfTM4Vb+TLKgMJ1myuNXAGRT3bJlv5dS3vZLN4EbLxmigZgNR8Fo2mhajPAzdrT2AEutOBxN59WtKGRv/'
        '9ZlE34AFmLTBkctlubor8RFxS1STY+j1Uc4rTaYezG1CLwbXPIzYoeYIrZNVVYRV4SMzbTP7IpdigBBBiDB2LeYKRzPp1a3vc8/J'
        'LtlKr+MdGzFqMyjdlRLfcYYxwLyOtOWjI1q8dLDLcY6uBz8ZBIdVS7o1huCFOJQnaU21CHb7e8saa5EL/05hbEcvnMgyf28ruZWD'
        'U3WZj5AwmjTD+uOYKer3igjypkK63iU+YOYdU8TsFOocUHaqzahbc6BoE7x8SosQ5pWkaujj+bwVHe44fG3x9eAX/0zt3IPYha70'
        'gOt26OjCyYjSfbtT9F1yefrBTrT5sZLPvrmjV2+Ll7rpBDnUyysnQnDUnpV1U6sxqvhMU10HbEzXOX3mj8YT6swYbtreVAd/fbae'
        'ee2M1E1jJRSbXxBYNwucZKojSkyf7YxIqhMLcCled80YWr0aIJVz27KQz13ZfXxVEH/zoLGerauWKWHwoyS/15iX6cnP6VsX0AnK'
        'WnLvS8ZWthHHGoYKrHPyzZtmcGaLW0OnK5riyDJ1gq4zUh5XV1ja47RYBMKKSaPg3aNP/XiGm9fnWyFez4fElqkD6pl8RmXpWms/'
        '/vnfdJFxzCkyzgAQXC/ERScK0c0yuNdxDFb95HC6seR4JiCtoCyIw3Un9p3oD6lcjmzEqqbcXba0HCzO3FbsphHZ6I7GPC8OxgFL'
        'Y+7UQe14DBLEEF4xlNId84oiwUIWjom2BHiwmqZnDygRSlhMft2tcxbTyCoJjSPJsMA6csglvDGGYM+rqnxxO+XIq85aSpJzZUwl'
        '1pXgOD3GNeSMoHVgBLGiuFUY/eVmgBWeMJTWImFVrj/Z0qWUEW+wZydYXNsokN61GQta5tYZnO1ktJeOVL2uX2XrlY65tMSym8ZF'
        '626vtvbJnqKDTx4ygOpT8XcxEQNtAmVPGexm0NKtAo0FFJPQOPArGrnMsmRsWn8HtS3x2f7MPiudwYMEx9KLUFFbiFS8UdJdVm70'
        '3cDpS4m0JnaQV8VYLZ2KBSQEgOea8FJsJC8vIgNDF06bHbSQiRRikY3WGjGlfV2cOrsiQdMJC4aV8u8EC/K47VXNCHlY9JusKnsz'
        '5i8uirIffqubt9qEc5uQSRiBgij8agtJWdVhTz+h4dRNQLi++OmXf/zzHzbCi5zqKBc8daP3gpoIYSXZEhhzkq9UX3U6iCGgdTvh'
        'Mu6FWDZ4E2BdHyehVwxTjDCyzTtCiMp0/1pGteoLfJsFIh5WxItZgqYHAAT8oqT3vQrHcA5e6PL55amFh5s6AIIh+PF4Ggyg1ikV'
        'NwKDVKeK6QiU4POGmG00BEPdsCvganstatHJrfuEEWcHLMVw0OolfXMJfKkx9VRI2riWOxGi6zAQRpPzjSeBhwE5rkifhDb8vhyp'
        '8VCaL8ouHBkE1Ikigan5Wq2RIYSOz1HkoSGyuEOgAYlSbqaWjr5vT603He2WmAJNf+q3TSvwdYif29vxufqGqb0Tx+Yk4iGzdlfc'
        'FpOpbvHTLzf4hCuC0oO2ztS3Ts0uqqawUToTqVpE6496KN85ojVFqBbUdASBo0ADktHhUECnfjGmsdkdgez2TfoCWCP6uap5LRyS'
        'YSk4h1graTHz2wjExQ5UcwcuduSNT+utNGAxuXl0VsGoMdQ9S8upwcPXn4Vnt4+h7Wt1A7xXesJ2skM/rOUGYiorv0VY1g1LXAXE'
        'V3fEPNFbdW2zTj39TCWudHLrjtzeeOCk4oqkQQ0CJz03yRhBpgqyx8YJVeDMV8revHn3xHRelqV9AMSJqWT4S/B20JdNeAxz6Dsk'
        'b039/kDy2bzp8vHZ5jUKk4IkObIgRPTO+23ZBvlQOQM+08+gYOUrzeWZoO2KI2zYyTx1t/KHLNMoBhyffH4O1wCztU10n3BkwXz3'
        'KUPcfYKmug8slZlL159YJL1MHp8xqHVG1tYRDj76pRe9nimwGJWEaK8iOxVWFHaTXDIa0LberRRXFcCghyCFN33aR0qnYLxMaOlH'
        'wpEy3wp6Q6vBSkn0eB4mbzGhFtyWST+Xss6uM7VBoqeEPexyVyGAcwTpN+KNPX1vrxzwPng90HqiewHq3pvfNKuWe4ogsHIraA4+'
        'P7GI3Y6DA6CO1X7fCxrwJP1CgXNjYI83x4mV4UCXcywEkisCUL0/gtUHpr7bVDyHNuiIgaCbvlQbihf6paJwp+Wc0nE/mjNXJNDd'
        'z2bYRtvYJcOjrajw52hMEbS86C70xdP5VYbb1sFxGszvEqnpV4C3wnuWkdKCyEBgiA4kMlw6P1VCPvX17aIOJhh71lTVfqfzbajz'
        'HtndGXRpfp0pAS34r+eYvCQ+AaCTJQglNEfdVBwy8f1Ncvk2IFf8avdEXv/bV6534iR7nkTJQvSawFat1ke5fY1WYJq+1AAJnMR8'
        'LNJ5mACmyRd+L0T9wrJlYKprtbBpVhHvbHQwbuP6Z5hS6KA0oc36ksA3MgPGWXvjNNr2mWrs2p8TwebGY0GIyu6yAZyUl73fpakZ'
        'EA63lqKVeQ6fiSvksWlgyGWhNtUiC+zpESOWoZXmp8i0XxBTmbrxo+3kuE9lQXYTYLEucJ+KBKj6Qf6JfuxZNcnaqKYz0mJb/VNl'
        'RER8G7Yuo+2S7TSj5wg1APGA5i4gTNHPbyf4u6CLjyV77ReieJmA8vRJWL8Vr9YrEVcioR8k/hLDF1s3HF2j3647kd+uQxbYcBK/'
        'J4dg+CN2nsqjre4EHNvrgY5/4RStufHBWGNboI+zMDgosCasLWHdH8uyVgqni1IPKnwo7Y9f+Qa6mThBdPOTyVulS3TwzlqJnbBJ'
        'XNiv0znUSjdy8Gq7o01QqnYDvfEZtwvWYHxSrH53CdQd5/V4FB1450j1c2rddmAdeNR1VtN5wzjmnUVs/9UYDl2yJPUin4hXGhHa'
        'QQKgNGKtm8Y+h8UK7dk3+bWl6F5cD3qaLqk7GuvCZOQ5XVlr16DKCgg+KH29atvhY8MqHgfI1+gHKAA5wCD8YsBg8d+nRv13nVmk'
        '7LYHanPLGGY1SCIHv8dNkwxMNs5zwCBR77379poKGB0LO77mdl/X4GIPY7Z4GhjiS1r4vpbKpnfFTEBwkJ1XhtRE/uK7BuJP8AqL'
        'RSUjwNKXSJfexCoj0EDJNG/4He1VJ93iv44QWZypRMFWE1rMds8bCojYuYtUG94l61QR5gf9bI2i5tsoEGhMa+VqgMvCrwo1Tyks'
        'eYiTaVqDB8A9bF7ueUfrTVUAu+3SXvXZEcer6UPTyf+U3nAlKJiRLx2EB7Mgp3UuLZcGZIvbalhAtqtOvsia7S5PFqP5/k740kVK'
        'VjrICBhxQCrP5q12vSQYSxXm6Zdlf/C5yMhI8h8Hbd3PDK61Gq/uxioaSKCbzCAB4FLXFYzmMtEx3k6kx9tPKy9x3ZXtQW77+Xvb'
        '9Mqu6kOGxcykyzoRMUrm6FnHScPIkNCsYZB83m4pa5cZzLMuA1ZbO0/eVUj/kzeA+qThPFV1SxqxysyMbgfcWBrPA5rH3mMMqNpG'
        'gqxJ8HzBjxRufuRqiy68KBeYpHXn0n2tc+m+oqRfmLwfSyz/bAl9ok4tumymLo3GT8c0lWXpOtGEkuvYDpR0BMNsXPhbEB5O5+Na'
        'p/JxndIM0b6gTx6UzQTggE1Li/sjJ63VurxTmpG7+YL2uDMqpSWTfhF8ndB/j2ubfiTQtaRgiNNEkhFX4xIwZbDPS/t84PbnEhwD'
        'f+FIiofZxE5sEeSyiZExWCZXD00nFlaZodKlGIJZHzPlYPnGaAuJ/AbiEKcb08BBWQavsTvrUadOt7GITBg08DGEajz9m0XxDxa5'
        'PRUQ9pDTm3Iai5W/pbKfwS1cA2yS0oT7260/Y0CSqyuv31k6PX2oNykIg6SFZ2ckbSEtxQql8hYq5qErt0mtNraQLgBfhwtivmLG'
        'BWpFKcKha2rzG+lzOwOpuwNbe+zaaWkmVYDJDwy4OfJ0V8rX5z3/ND8s6RIw+XVKi2oqqdJeVA76YfNTL6p97qrShX0pqenUKaL0'
        'v5Mt2e1FEFWWoOqoMQ984EMz7X+yniH9Sfi1gPA3Mr4Y5CVKxUcRkoYvIJMsfBRhPjwKsPR7SJb5B90KBMfxVgeLJITN4PGr7Pv6'
        'FcKpJn7WyPHclPDsjzhwA1z/2sjnaOKHk+7ryl2o0z5VyQtuXWf12Q33fX3MXR9riLsvjUwksmjoFejpn7vagorynnjyTfbbXNjE'
        'PrSSLTsGOQ7N0ST65oDL/23JcDn52W11wDMB565sQ5bwiirAk7fWmueze2vL9Bmeu7sG/LPb64BnAp4ajqkbuwDPDsfUrTXg8b01'
        'UD+3KoBr4lrawbmLacuQvZqeYmCX05bxW66nHW/ugnqKwV9Rq/X8tcQr3ht1KhM7m31/Ls2xEJ0cd+rgYP21Zll/XVwODfk9JqNQ'
        'THzJJbjCLepcSw9l1zItX9ifKTDdett+tj4ZRxbMCSNnCEWRoUlBfNt+uirftlNrEtHcinzbhhnnTaFkInpX6LNFzDiyYH7MppYv'
        'QzNjNrV037Z84bpq++2xpZ/pt+0H+1vHtZC/67BAHZawEXr43YlF/7adXPIIZxd8HmbL/W37rYvdcOaWeh5msSg2HNF73vDHWn3e'
        '8ZCacA6bn5xKuGo1kqS73J3G22obxDIJEhMI7LadktQou7GCltHvItA7VP1WILhkhSsve3x7BE3GDD/zo2zm1YF/HIHXqkAz7mB/'
        '6mnHocUx0yfGgvxmY7nbeUgV+n+hrIj8'
    ),
}
