"""Execute real Java helper classes on a JVM with small Android boundary fakes.

Set CORE_WORKER_JSON_JAR to org.json:json:20240303 and, without javac,
CORE_WORKER_ECJ_JAR to Eclipse ECJ. No network or downloads happen in tests.
"""
from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import io
import tarfile

import pytest

ROOT = Path(__file__).resolve().parents[1]
JAVA = ROOT / "android/core-worker-app/app/src/main/java/dev/core/worker"


@pytest.fixture(scope="session")
def java_harness(tmp_path_factory):
    java = shutil.which("java")
    javac = shutil.which("javac")
    ecj = os.environ.get("CORE_WORKER_ECJ_JAR", "")
    json_jar = os.environ.get("CORE_WORKER_JSON_JAR", "")
    if not java or not Path(json_jar).is_file() or not (javac or Path(ecj).is_file()):
        message = "Java harness requires java, javac (or CORE_WORKER_ECJ_JAR) and CORE_WORKER_JSON_JAR"
        if os.environ.get("CORE_WORKER_REQUIRE_JAVA_TESTS") == "1":
            pytest.fail(message)
        pytest.skip(message)
    output = tmp_path_factory.mktemp("core-worker-java")
    classes = ["CoreWorkerRuntimeIdentity", "CoreWorkerAutoEnrollment", "CoreWorkerSocketListener",
               "CoreWorkerHttpTransport", "CoreWorkerUpdateArtifacts", "CoreWorkerBackgroundIo",
               "LocalNativeTtsHttpServer", "CoreWorkerDirectHttpServer",
               "CoreLinuxRootfsFilesystem", "CoreLinuxRootfsTarExtractor", "CoreWorkerAtomicTextFiles",
               "CoreWorkerApkToolchainFilesystem", "CoreWorkerProcessRunner", "CoreWorkerNativeCalls"]
    sources = [str(JAVA / (name + ".java")) for name in classes]
    sources += [str(p) for directory in [ROOT / "tests/java_support", ROOT / "tests/java_harness"]
                for p in sorted(directory.rglob("*.java"))]
    command = [javac, "--release", "17"] if javac else [java, "-jar", ecj, "-17", "-nowarn"]
    compile_run = subprocess.run(command + ["-encoding", "UTF-8", "-cp", json_jar, "-d", str(output), *sources],
                                 capture_output=True, text=True, timeout=90)
    assert compile_run.returncode == 0, compile_run.stdout + compile_run.stderr
    return [java, "-ea", "-cp", os.pathsep.join([str(output), json_jar]), "dev.core.worker.WorkerHarness"]


@pytest.mark.parametrize("scenario", [
    "install_concurrent", "install_commit_failure", "migration_idempotent", "pair_atomic", "pair_failure",
    "challenge_concurrent", "challenge_failure", "clear_stale_heartbeat", "stop_stale_heartbeat",
    "listener_restart", "listener_bounded", "listener_failure_recovery", "direct_restart",
    "tts_bind_failure", "tts_restart", "http_bounded", "http_redirect",
    "update_origin", "update_hash", "update_size", "update_chunked_size", "update_partial",
    "update_redirect", "update_success", "fcm_latest_wins",
    "fs_nofollow", "fs_rootfs_promotion", "fs_rootfs_recovery", "fs_rootfs_missing_staging",
    "fs_atomic_roundtrip", "fs_atomic_failure", "fs_atomic_recovery", "fs_atomic_short_reads",
    "fs_tar_normal", "fs_tar_traversal", "fs_tar_absolute", "fs_tar_hardlink", "fs_tar_symlink_external",
    "fs_tar_symlink_failure", "fs_tar_metadata_count", "fs_tar_metadata_size", "fs_tar_pax_traversal",
    "fs_tar_pax_unicode", "fs_tar_symlink_ok", "fs_tar_checksum", "fs_tar_gzip_truncated",
    "fs_toolchain_success", "fs_toolchain_crash_before_next", "fs_toolchain_crash_after_next",
    "fs_toolchain_intent_failure", "fs_toolchain_confirm_failure", "fs_toolchain_rollback",
    "recovery_overlapping_paths", "recovery_atomic_silent_finish",
    "recovery_binary_replacement", "recovery_reuse_pending",
    "recovery_metadata_symlink_manifest", "recovery_metadata_symlink_marker", "recovery_missing_manifest",
    "recovery_confirm_failure_same_process", "recovery_confirm_failure_reopen",
    "recovery_rollback_commit_failure", "recovery_rollback_after_failed", "recovery_rollback_after_restore",
    "process_flood", "process_limits", "process_timeout", "process_interrupt", "process_descendant",
    "native_timeout", "native_interrupt", "process_collector_failure", "process_start_failure",
])
def test_java_worker_behavior(java_harness, scenario):
    result = subprocess.run([*java_harness, scenario], capture_output=True, text=True, timeout=25)
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.parametrize("format", [tarfile.USTAR_FORMAT, tarfile.PAX_FORMAT, tarfile.GNU_FORMAT])
def test_java_tar_interoperability(java_harness, tmp_path, format):
    archive, target = tmp_path / "rootfs.tar.gz", tmp_path / "staging"
    target.mkdir()
    # Generated by Python's standard TAR writer, independently of our Java
    # fixture builder. Include legitimate whitespace and relative symlink names.
    names = ["usr/share/empty", "usr/share/ spaced "]
    if format != tarfile.USTAR_FORMAT:
        names.append("usr/share/á-" + "long-name-" * 20 + " ")
    with tarfile.open(archive, "w:gz", format=format) as tar:
        for name in names:
            content = b"" if name.endswith("empty") else "conteúdo".encode()
            entry = tarfile.TarInfo(name)
            entry.size = len(content)
            tar.addfile(entry, io.BytesIO(content))
        link = tarfile.TarInfo("usr/share/link")
        link.type = tarfile.SYMTYPE
        link.linkname = " spaced "
        tar.addfile(link)
    result = subprocess.run([*java_harness, "tar_external", str(archive), str(target)],
                            capture_output=True, text=True, timeout=10)
    assert result.returncode == 0, result.stdout + result.stderr
    for name in names:
        assert (target / name).read_bytes() == (b"" if name.endswith("empty") else "conteúdo".encode())
    assert os.readlink(target / "usr/share/link") == " spaced "
    assert (target / "usr/share/link").read_bytes() == "conteúdo".encode()
