// Complete tts_langs() catalog from gTTS 2.5.4, pinned in requirements.txt.
// Keep provider codes (including iw, jw and region casing) when updating labels.
export const TTS_LANGUAGE_OPTIONS = [
  { value: "af", label: "Africâner" },
  { value: "sq", label: "Albanês" },
  { value: "de", label: "Alemão" },
  { value: "am", label: "Amárico" },
  { value: "ar", label: "Árabe" },
  { value: "eu", label: "Basco" },
  { value: "bn", label: "Bengali" },
  { value: "my", label: "Birmanês" },
  { value: "bs", label: "Bósnio" },
  { value: "bg", label: "Búlgaro" },
  { value: "kn", label: "Canarim" },
  { value: "yue", label: "Cantonês" },
  { value: "ca", label: "Catalão" },
  { value: "zh", label: "Chinês (mandarim)" },
  { value: "zh-CN", label: "Chinês (simplificado)" },
  { value: "zh-TW", label: "Chinês (tradicional, Taiwan)" },
  { value: "si", label: "Cingalês" },
  { value: "ko", label: "Coreano" },
  { value: "hr", label: "Croata" },
  { value: "da", label: "Dinamarquês" },
  { value: "sk", label: "Eslovaco" },
  { value: "es", label: "Espanhol" },
  { value: "et", label: "Estoniano" },
  { value: "tl", label: "Filipino" },
  { value: "fi", label: "Finlandês" },
  { value: "fr", label: "Francês" },
  { value: "fr-CA", label: "Francês (Canadá)" },
  { value: "gl", label: "Galego" },
  { value: "cy", label: "Galês" },
  { value: "el", label: "Grego" },
  { value: "gu", label: "Guzerate" },
  { value: "ha", label: "Hauçá" },
  { value: "iw", label: "Hebraico" },
  { value: "hi", label: "Hindi" },
  { value: "nl", label: "Holandês" },
  { value: "hu", label: "Húngaro" },
  { value: "id", label: "Indonésio" },
  { value: "en", label: "Inglês" },
  { value: "is", label: "Islandês" },
  { value: "it", label: "Italiano" },
  { value: "ja", label: "Japonês" },
  { value: "jw", label: "Javanês" },
  { value: "km", label: "Khmer" },
  { value: "la", label: "Latim" },
  { value: "lv", label: "Letão" },
  { value: "lt", label: "Lituano" },
  { value: "ml", label: "Malaiala" },
  { value: "ms", label: "Malaio" },
  { value: "mr", label: "Marati" },
  { value: "ne", label: "Nepalês" },
  { value: "no", label: "Norueguês" },
  { value: "pl", label: "Polonês" },
  { value: "pt", label: "Português (Brasil)" },
  { value: "pt-PT", label: "Português (Portugal)" },
  { value: "pa", label: "Punjabi (gurmukhi)" },
  { value: "ro", label: "Romeno" },
  { value: "ru", label: "Russo" },
  { value: "sr", label: "Sérvio" },
  { value: "sw", label: "Suaíli" },
  { value: "sv", label: "Sueco" },
  { value: "su", label: "Sundanês" },
  { value: "th", label: "Tailandês" },
  { value: "ta", label: "Tâmil" },
  { value: "cs", label: "Tcheco" },
  { value: "te", label: "Télugo" },
  { value: "tr", label: "Turco" },
  { value: "uk", label: "Ucraniano" },
  { value: "ur", label: "Urdu" },
  { value: "vi", label: "Vietnamita" },
];
